# coding: utf-8

"""
    Affinity API

    Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

    The version of the OpenAPI document: 2026-07-09
    Contact: support@joinaffinityai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from affinity_sdk.models.create_practice_request_attestations import CreatePracticeRequestAttestations

class TestCreatePracticeRequestAttestations(unittest.TestCase):
    """CreatePracticeRequestAttestations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePracticeRequestAttestations:
        """Test CreatePracticeRequestAttestations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePracticeRequestAttestations`
        """
        model = CreatePracticeRequestAttestations()
        if include_optional:
            return CreatePracticeRequestAttestations(
                authorized_phi_transfer = True,
                authorized_practice_relationship = True,
                minimum_necessary_phi = True,
                provider_data_accuracy = True
            )
        else:
            return CreatePracticeRequestAttestations(
                authorized_phi_transfer = True,
                authorized_practice_relationship = True,
                minimum_necessary_phi = True,
                provider_data_accuracy = True,
        )
        """

    def testCreatePracticeRequestAttestations(self):
        """Test CreatePracticeRequestAttestations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
