# coding: utf-8

"""
    Affinity API

    Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

    The version of the OpenAPI document: 2026-07-09
    Contact: support@joinaffinityai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from affinity_sdk.api.catalog_api import CatalogApi


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogApi()

    def tearDown(self) -> None:
        pass

    def test_list_catalog_items(self) -> None:
        """Test case for list_catalog_items

        List catalog items
        """
        pass


if __name__ == '__main__':
    unittest.main()
