# coding: utf-8

"""
    Affinity API

    Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

    The version of the OpenAPI document: 2026-07-09
    Contact: support@joinaffinityai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from affinity_sdk.models.list_webhook_events200_response import ListWebhookEvents200Response

class TestListWebhookEvents200Response(unittest.TestCase):
    """ListWebhookEvents200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWebhookEvents200Response:
        """Test ListWebhookEvents200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWebhookEvents200Response`
        """
        model = ListWebhookEvents200Response()
        if include_optional:
            return ListWebhookEvents200Response(
                events = [
                    affinity_sdk.models.list_webhook_events_200_response_events_inner.listWebhookEvents_200_response_events_inner(
                        created_at = '', 
                        event_type = '', 
                        id = '', 
                        livemode = True, 
                        object_id = '', 
                        object_type = '', 
                        updated_at = '', )
                    ]
            )
        else:
            return ListWebhookEvents200Response(
                events = [
                    affinity_sdk.models.list_webhook_events_200_response_events_inner.listWebhookEvents_200_response_events_inner(
                        created_at = '', 
                        event_type = '', 
                        id = '', 
                        livemode = True, 
                        object_id = '', 
                        object_type = '', 
                        updated_at = '', )
                    ],
        )
        """

    def testListWebhookEvents200Response(self):
        """Test ListWebhookEvents200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
