# coding: utf-8

"""
    Affinity API

    Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

    The version of the OpenAPI document: 2026-07-09
    Contact: support@joinaffinityai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from affinity_sdk.models.update_order_request import UpdateOrderRequest

class TestUpdateOrderRequest(unittest.TestCase):
    """UpdateOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrderRequest:
        """Test UpdateOrderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrderRequest`
        """
        model = UpdateOrderRequest()
        if include_optional:
            return UpdateOrderRequest(
                quantity = 1.337
            )
        else:
            return UpdateOrderRequest(
        )
        """

    def testUpdateOrderRequest(self):
        """Test UpdateOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
