# coding: utf-8

"""
    Affinity API

    Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

    The version of the OpenAPI document: 2026-07-09
    Contact: support@joinaffinityai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from affinity_sdk.models.list_catalog_items200_response import ListCatalogItems200Response

class TestListCatalogItems200Response(unittest.TestCase):
    """ListCatalogItems200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCatalogItems200Response:
        """Test ListCatalogItems200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCatalogItems200Response`
        """
        model = ListCatalogItems200Response()
        if include_optional:
            return ListCatalogItems200Response(
                items = [
                    affinity_sdk.models.list_catalog_items_200_response_items_inner.listCatalogItems_200_response_items_inner(
                        allowed_states = [
                            ''
                            ], 
                        catalog_kind = '', 
                        cold_ship = True, 
                        compounder_id = '', 
                        compounder_name = '', 
                        description = '', 
                        dosage_form = '', 
                        facility_type = '', 
                        id = '', 
                        is_orderable = True, 
                        name = '', 
                        patient_specific_required = True, 
                        restricted_states = [
                            ''
                            ], 
                        route = '', 
                        strength = '', )
                    ]
            )
        else:
            return ListCatalogItems200Response(
                items = [
                    affinity_sdk.models.list_catalog_items_200_response_items_inner.listCatalogItems_200_response_items_inner(
                        allowed_states = [
                            ''
                            ], 
                        catalog_kind = '', 
                        cold_ship = True, 
                        compounder_id = '', 
                        compounder_name = '', 
                        description = '', 
                        dosage_form = '', 
                        facility_type = '', 
                        id = '', 
                        is_orderable = True, 
                        name = '', 
                        patient_specific_required = True, 
                        restricted_states = [
                            ''
                            ], 
                        route = '', 
                        strength = '', )
                    ],
        )
        """

    def testListCatalogItems200Response(self):
        """Test ListCatalogItems200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
