# coding: utf-8

"""
    Affinity API

    Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

    The version of the OpenAPI document: 2026-07-19
    Contact: support@joinaffinityai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetWebhookEventResponseAttemptsInner(BaseModel):
    """
    GetWebhookEventResponseAttemptsInner
    """ # noqa: E501
    attempted_at: StrictStr = Field(alias="attemptedAt")
    error_message: Optional[StrictStr] = Field(alias="errorMessage")
    id: Annotated[str, Field(strict=True)]
    response_body: Optional[StrictStr] = Field(alias="responseBody")
    response_status: Optional[Union[StrictFloat, StrictInt]] = Field(alias="responseStatus")
    success: StrictBool
    __properties: ClassVar[List[str]] = ["attemptedAt", "errorMessage", "id", "responseBody", "responseStatus", "success"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^wha_[0-9a-hjkmnp-tv-z]{26}$", value):
            raise ValueError(r"must validate the regular expression /^wha_[0-9a-hjkmnp-tv-z]{26}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetWebhookEventResponseAttemptsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if response_body (nullable) is None
        # and model_fields_set contains the field
        if self.response_body is None and "response_body" in self.model_fields_set:
            _dict['responseBody'] = None

        # set to None if response_status (nullable) is None
        # and model_fields_set contains the field
        if self.response_status is None and "response_status" in self.model_fields_set:
            _dict['responseStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetWebhookEventResponseAttemptsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attemptedAt": obj.get("attemptedAt"),
            "errorMessage": obj.get("errorMessage"),
            "id": obj.get("id"),
            "responseBody": obj.get("responseBody"),
            "responseStatus": obj.get("responseStatus"),
            "success": obj.get("success")
        })
        return _obj


