# coding: utf-8

"""
    Affinity API

    Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

    The version of the OpenAPI document: 2026-07-19
    Contact: support@joinaffinityai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from affinity_sdk.models.problem_error import ProblemError
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Problem(BaseModel):
    """
    Problem
    """ # noqa: E501
    code: Annotated[str, Field(strict=True)]
    detail: StrictStr
    errors: Optional[List[ProblemError]] = None
    instance: Annotated[str, Field(strict=True)]
    request_id: Annotated[str, Field(strict=True)] = Field(alias="requestId")
    status: Annotated[int, Field(le=599, strict=True, ge=400)]
    title: StrictStr
    type: Annotated[str, Field(strict=True)]
    __properties: ClassVar[List[str]] = ["code", "detail", "errors", "instance", "requestId", "status", "title", "type"]

    @field_validator('code')
    def code_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-z][a-z0-9_]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z][a-z0-9_]*$/")
        return value

    @field_validator('instance')
    def instance_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^urn:affinity:request:req_[0-9a-hjkmnp-tv-z]{26}$", value):
            raise ValueError(r"must validate the regular expression /^urn:affinity:request:req_[0-9a-hjkmnp-tv-z]{26}$/")
        return value

    @field_validator('request_id')
    def request_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^req_[0-9a-hjkmnp-tv-z]{26}$", value):
            raise ValueError(r"must validate the regular expression /^req_[0-9a-hjkmnp-tv-z]{26}$/")
        return value

    @field_validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^https:\/\/docs\.joinaffinityai\.com\/errors\/", value):
            raise ValueError(r"must validate the regular expression /^https:\/\/docs\.joinaffinityai\.com\/errors\//")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Problem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['errors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Problem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "detail": obj.get("detail"),
            "errors": [ProblemError.from_dict(_item) for _item in obj["errors"]] if obj.get("errors") is not None else None,
            "instance": obj.get("instance"),
            "requestId": obj.get("requestId"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "type": obj.get("type")
        })
        return _obj


