/*
Affinity API

Testing CatalogAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package affinity

import (
	"context"
	openapiclient "github.com/Dawsson/affinity-libraries/go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_affinity_CatalogAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CatalogAPIService ListCatalogItems", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CatalogAPI.ListCatalogItems(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
