/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import ai.joinaffinity.sdk.model.CreateOrderRequestAnyOf;
import ai.joinaffinity.sdk.model.CreateOrderRequestAnyOf1;
import ai.joinaffinity.sdk.model.CreateOrderRequestAnyOf1ShippingAddress;
import ai.joinaffinity.sdk.model.CreateOrderRequestAnyOfPatient;
import ai.joinaffinity.sdk.model.CreateOrderRequestAnyOfPrescriber;
import ai.joinaffinity.sdk.model.CreateOrderRequestAnyOfPrescription;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateOrderRequest
 */
class CreateOrderRequestTest {
    private final CreateOrderRequest model = new CreateOrderRequest();

    /**
     * Model tests for CreateOrderRequest
     */
    @Test
    void testCreateOrderRequest() {
        // TODO: test CreateOrderRequest
    }

    /**
     * Test the property 'catalogItemId'
     */
    @Test
    void catalogItemIdTest() {
        // TODO: test catalogItemId
    }

    /**
     * Test the property 'practiceId'
     */
    @Test
    void practiceIdTest() {
        // TODO: test practiceId
    }

    /**
     * Test the property 'directions'
     */
    @Test
    void directionsTest() {
        // TODO: test directions
    }

    /**
     * Test the property 'externalOrderId'
     */
    @Test
    void externalOrderIdTest() {
        // TODO: test externalOrderId
    }

    /**
     * Test the property 'patient'
     */
    @Test
    void patientTest() {
        // TODO: test patient
    }

    /**
     * Test the property 'prescriber'
     */
    @Test
    void prescriberTest() {
        // TODO: test prescriber
    }

    /**
     * Test the property 'prescription'
     */
    @Test
    void prescriptionTest() {
        // TODO: test prescription
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'replacesOrderId'
     */
    @Test
    void replacesOrderIdTest() {
        // TODO: test replacesOrderId
    }

    /**
     * Test the property 'pharmacyOrganizationId'
     */
    @Test
    void pharmacyOrganizationIdTest() {
        // TODO: test pharmacyOrganizationId
    }

    /**
     * Test the property 'prescriptionId'
     */
    @Test
    void prescriptionIdTest() {
        // TODO: test prescriptionId
    }

    /**
     * Test the property 'prescriptionVersionId'
     */
    @Test
    void prescriptionVersionIdTest() {
        // TODO: test prescriptionVersionId
    }

    /**
     * Test the property 'registeredLocationId'
     */
    @Test
    void registeredLocationIdTest() {
        // TODO: test registeredLocationId
    }

    /**
     * Test the property 'shippingAddress'
     */
    @Test
    void shippingAddressTest() {
        // TODO: test shippingAddress
    }

}
