/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import ai.joinaffinity.sdk.model.ListPractices200ResponseDataInnerContactsPrimary;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePractice200ResponseContacts
 */
class CreatePractice200ResponseContactsTest {
    private final CreatePractice200ResponseContacts model = new CreatePractice200ResponseContacts();

    /**
     * Model tests for CreatePractice200ResponseContacts
     */
    @Test
    void testCreatePractice200ResponseContacts() {
        // TODO: test CreatePractice200ResponseContacts
    }

    /**
     * Test the property 'compliance'
     */
    @Test
    void complianceTest() {
        // TODO: test compliance
    }

    /**
     * Test the property 'primary'
     */
    @Test
    void primaryTest() {
        // TODO: test primary
    }

}
