/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import ai.joinaffinity.sdk.model.GetPlatformOrganization200ResponseAccount;
import ai.joinaffinity.sdk.model.GetPlatformOrganization200ResponseMembership;
import ai.joinaffinity.sdk.model.GetPlatformOrganization200ResponseUser;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetPlatformOrganization200Response
 */
class GetPlatformOrganization200ResponseTest {
    private final GetPlatformOrganization200Response model = new GetPlatformOrganization200Response();

    /**
     * Model tests for GetPlatformOrganization200Response
     */
    @Test
    void testGetPlatformOrganization200Response() {
        // TODO: test GetPlatformOrganization200Response
    }

    /**
     * Test the property 'account'
     */
    @Test
    void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'membership'
     */
    @Test
    void membershipTest() {
        // TODO: test membership
    }

    /**
     * Test the property 'user'
     */
    @Test
    void userTest() {
        // TODO: test user
    }

}
