/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import ai.joinaffinity.sdk.model.GetWebhookEvent200ResponseAttemptsInner;
import ai.joinaffinity.sdk.model.GetWebhookEvent200ResponseDeliveriesInner;
import ai.joinaffinity.sdk.model.GetWebhookEvent200ResponseEvent;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetWebhookEvent200Response
 */
class GetWebhookEvent200ResponseTest {
    private final GetWebhookEvent200Response model = new GetWebhookEvent200Response();

    /**
     * Model tests for GetWebhookEvent200Response
     */
    @Test
    void testGetWebhookEvent200Response() {
        // TODO: test GetWebhookEvent200Response
    }

    /**
     * Test the property 'attempts'
     */
    @Test
    void attemptsTest() {
        // TODO: test attempts
    }

    /**
     * Test the property 'deliveries'
     */
    @Test
    void deliveriesTest() {
        // TODO: test deliveries
    }

    /**
     * Test the property 'event'
     */
    @Test
    void eventTest() {
        // TODO: test event
    }

}
