/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetWebhookEventResponse
 */
export interface GetWebhookEventResponse {
    /**
     *
     * @type {string}
     * @memberof GetWebhookEventResponse
     */
    createdAt: string;
    /**
     *
     * @type {string}
     * @memberof GetWebhookEventResponse
     */
    eventType: string;
    /**
     *
     * @type {boolean}
     * @memberof GetWebhookEventResponse
     */
    livemode: boolean;
    /**
     *
     * @type {GetWebhookEventResponseObjectEnum}
     * @memberof GetWebhookEventResponse
     */
    object: GetWebhookEventResponseObjectEnum;
    /**
     *
     * @type {string}
     * @memberof GetWebhookEventResponse
     */
    objectId: string;
    /**
     *
     * @type {string}
     * @memberof GetWebhookEventResponse
     */
    objectType: string;
    /**
     *
     * @type {string}
     * @memberof GetWebhookEventResponse
     */
    updatedAt: string;
}


/**
 * @export
 */
export const GetWebhookEventResponseObjectEnum = {
    WebhookEvent: 'webhook_event'
} as const;
export type GetWebhookEventResponseObjectEnum = typeof GetWebhookEventResponseObjectEnum[keyof typeof GetWebhookEventResponseObjectEnum];


/**
 * Check if a given object implements the GetWebhookEventResponse interface.
 */
export function instanceOfGetWebhookEventResponse(value: object): value is GetWebhookEventResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('livemode' in value) || value['livemode'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('objectId' in value) || value['objectId'] === undefined) return false;
    if (!('objectType' in value) || value['objectType'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetWebhookEventResponseFromJSON(json: any): GetWebhookEventResponse {
    return GetWebhookEventResponseFromJSONTyped(json, false);
}

export function GetWebhookEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebhookEventResponse {
    if (json == null) {
        return json;
    }
    return {

        'createdAt': json['createdAt'],
        'eventType': json['eventType'],
        'livemode': json['livemode'],
        'object': json['object'],
        'objectId': json['objectId'],
        'objectType': json['objectType'],
        'updatedAt': json['updatedAt'],
    };
}

export function GetWebhookEventResponseToJSON(json: any): GetWebhookEventResponse {
    return GetWebhookEventResponseToJSONTyped(json, false);
}

export function GetWebhookEventResponseToJSONTyped(value?: GetWebhookEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'createdAt': value['createdAt'],
        'eventType': value['eventType'],
        'livemode': value['livemode'],
        'object': value['object'],
        'objectId': value['objectId'],
        'objectType': value['objectType'],
        'updatedAt': value['updatedAt'],
    };
}

