/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListOrdersResponseDataInnerRouting } from './ListOrdersResponseDataInnerRouting';
import {
    ListOrdersResponseDataInnerRoutingFromJSON,
    ListOrdersResponseDataInnerRoutingFromJSONTyped,
    ListOrdersResponseDataInnerRoutingToJSON,
    ListOrdersResponseDataInnerRoutingToJSONTyped,
} from './ListOrdersResponseDataInnerRouting';

/**
 *
 * @export
 * @interface ListOrdersResponseDataInner
 */
export interface ListOrdersResponseDataInner {
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    cancellationReason: string | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    carrier: string | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    createdAt: string;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    currency: string;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    deliveredAt: string | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    directions: string;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    dosageForm: string | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    externalOrderId: string;
    /**
     *
     * @type {boolean}
     * @memberof ListOrdersResponseDataInner
     */
    externalSubmissionAttempted: boolean;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    externalSubmissionBlockedReason: string | null;
    /**
     *
     * @type {boolean}
     * @memberof ListOrdersResponseDataInner
     */
    livemode: boolean;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    medicationName: string;
    /**
     *
     * @type {ListOrdersResponseDataInnerObjectEnum}
     * @memberof ListOrdersResponseDataInner
     */
    object: ListOrdersResponseDataInnerObjectEnum;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    patientExternalId: string;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    patientName: string;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    patientState: string;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    prescriberName: string | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    prescriberNpi: string | null;
    /**
     *
     * @type {number}
     * @memberof ListOrdersResponseDataInner
     */
    quantity: number;
    /**
     *
     * @type {number}
     * @memberof ListOrdersResponseDataInner
     */
    quoteCents: number | null;
    /**
     *
     * @type {ListOrdersResponseDataInnerRouting}
     * @memberof ListOrdersResponseDataInner
     */
    routing: ListOrdersResponseDataInnerRouting | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    shippedAt: string | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    strength: string | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    trackingNumber: string | null;
    /**
     *
     * @type {string}
     * @memberof ListOrdersResponseDataInner
     */
    updatedAt: string;
}


/**
 * @export
 */
export const ListOrdersResponseDataInnerObjectEnum = {
    Order: 'order'
} as const;
export type ListOrdersResponseDataInnerObjectEnum = typeof ListOrdersResponseDataInnerObjectEnum[keyof typeof ListOrdersResponseDataInnerObjectEnum];


/**
 * Check if a given object implements the ListOrdersResponseDataInner interface.
 */
export function instanceOfListOrdersResponseDataInner(value: object): value is ListOrdersResponseDataInner {
    if (!('cancellationReason' in value) || value['cancellationReason'] === undefined) return false;
    if (!('carrier' in value) || value['carrier'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('deliveredAt' in value) || value['deliveredAt'] === undefined) return false;
    if (!('directions' in value) || value['directions'] === undefined) return false;
    if (!('dosageForm' in value) || value['dosageForm'] === undefined) return false;
    if (!('externalOrderId' in value) || value['externalOrderId'] === undefined) return false;
    if (!('externalSubmissionAttempted' in value) || value['externalSubmissionAttempted'] === undefined) return false;
    if (!('externalSubmissionBlockedReason' in value) || value['externalSubmissionBlockedReason'] === undefined) return false;
    if (!('livemode' in value) || value['livemode'] === undefined) return false;
    if (!('medicationName' in value) || value['medicationName'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('patientExternalId' in value) || value['patientExternalId'] === undefined) return false;
    if (!('patientName' in value) || value['patientName'] === undefined) return false;
    if (!('patientState' in value) || value['patientState'] === undefined) return false;
    if (!('prescriberName' in value) || value['prescriberName'] === undefined) return false;
    if (!('prescriberNpi' in value) || value['prescriberNpi'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('quoteCents' in value) || value['quoteCents'] === undefined) return false;
    if (!('routing' in value) || value['routing'] === undefined) return false;
    if (!('shippedAt' in value) || value['shippedAt'] === undefined) return false;
    if (!('strength' in value) || value['strength'] === undefined) return false;
    if (!('trackingNumber' in value) || value['trackingNumber'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ListOrdersResponseDataInnerFromJSON(json: any): ListOrdersResponseDataInner {
    return ListOrdersResponseDataInnerFromJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrdersResponseDataInner {
    if (json == null) {
        return json;
    }
    return {

        'cancellationReason': json['cancellationReason'],
        'carrier': json['carrier'],
        'createdAt': json['createdAt'],
        'currency': json['currency'],
        'deliveredAt': json['deliveredAt'],
        'directions': json['directions'],
        'dosageForm': json['dosageForm'],
        'externalOrderId': json['externalOrderId'],
        'externalSubmissionAttempted': json['externalSubmissionAttempted'],
        'externalSubmissionBlockedReason': json['externalSubmissionBlockedReason'],
        'livemode': json['livemode'],
        'medicationName': json['medicationName'],
        'object': json['object'],
        'patientExternalId': json['patientExternalId'],
        'patientName': json['patientName'],
        'patientState': json['patientState'],
        'prescriberName': json['prescriberName'],
        'prescriberNpi': json['prescriberNpi'],
        'quantity': json['quantity'],
        'quoteCents': json['quoteCents'],
        'routing': ListOrdersResponseDataInnerRoutingFromJSON(json['routing']),
        'shippedAt': json['shippedAt'],
        'strength': json['strength'],
        'trackingNumber': json['trackingNumber'],
        'updatedAt': json['updatedAt'],
    };
}

export function ListOrdersResponseDataInnerToJSON(json: any): ListOrdersResponseDataInner {
    return ListOrdersResponseDataInnerToJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerToJSONTyped(value?: ListOrdersResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'cancellationReason': value['cancellationReason'],
        'carrier': value['carrier'],
        'createdAt': value['createdAt'],
        'currency': value['currency'],
        'deliveredAt': value['deliveredAt'],
        'directions': value['directions'],
        'dosageForm': value['dosageForm'],
        'externalOrderId': value['externalOrderId'],
        'externalSubmissionAttempted': value['externalSubmissionAttempted'],
        'externalSubmissionBlockedReason': value['externalSubmissionBlockedReason'],
        'livemode': value['livemode'],
        'medicationName': value['medicationName'],
        'object': value['object'],
        'patientExternalId': value['patientExternalId'],
        'patientName': value['patientName'],
        'patientState': value['patientState'],
        'prescriberName': value['prescriberName'],
        'prescriberNpi': value['prescriberNpi'],
        'quantity': value['quantity'],
        'quoteCents': value['quoteCents'],
        'routing': ListOrdersResponseDataInnerRoutingToJSON(value['routing']),
        'shippedAt': value['shippedAt'],
        'strength': value['strength'],
        'trackingNumber': value['trackingNumber'],
        'updatedAt': value['updatedAt'],
    };
}

