/*
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class Pair {
  private final String name;
  private final String value;

  public Pair(String name, String value) {
    this.name = isValidString(name) ? name : "";
    this.value = isValidString(value) ? value : "";
  }

  public String getName() {
    return this.name;
  }

  public String getValue() {
    return this.value;
  }

  private static boolean isValidString(String arg) {
    return arg != null;
  }
}
