/*
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ai.joinaffinity.sdk.api;

import ai.joinaffinity.sdk.ApiClient;
import ai.joinaffinity.sdk.ApiException;
import ai.joinaffinity.sdk.ApiResponse;
import ai.joinaffinity.sdk.Configuration;
import ai.joinaffinity.sdk.Pair;

import ai.joinaffinity.sdk.model.CreatePractice200Response;
import ai.joinaffinity.sdk.model.CreatePracticeRequest;
import ai.joinaffinity.sdk.model.Error;
import ai.joinaffinity.sdk.model.ListPractices200Response;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class PracticesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PracticesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PracticesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create practice
   * Creates a platform-owned practice. Send Idempotency-Key to safely retry network failures.
   * @param createPracticeRequest  (required)
   * @return CreatePractice200Response
   * @throws ApiException if fails to make API call
   */
  public CreatePractice200Response createPractice(@javax.annotation.Nonnull CreatePracticeRequest createPracticeRequest) throws ApiException {
    return createPractice(createPracticeRequest, null);
  }

  /**
   * Create practice
   * Creates a platform-owned practice. Send Idempotency-Key to safely retry network failures.
   * @param createPracticeRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CreatePractice200Response
   * @throws ApiException if fails to make API call
   */
  public CreatePractice200Response createPractice(@javax.annotation.Nonnull CreatePracticeRequest createPracticeRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CreatePractice200Response> localVarResponse = createPracticeWithHttpInfo(createPracticeRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create practice
   * Creates a platform-owned practice. Send Idempotency-Key to safely retry network failures.
   * @param createPracticeRequest  (required)
   * @return ApiResponse&lt;CreatePractice200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreatePractice200Response> createPracticeWithHttpInfo(@javax.annotation.Nonnull CreatePracticeRequest createPracticeRequest) throws ApiException {
    return createPracticeWithHttpInfo(createPracticeRequest, null);
  }

  /**
   * Create practice
   * Creates a platform-owned practice. Send Idempotency-Key to safely retry network failures.
   * @param createPracticeRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreatePractice200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreatePractice200Response> createPracticeWithHttpInfo(@javax.annotation.Nonnull CreatePracticeRequest createPracticeRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createPracticeRequestBuilder(createPracticeRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createPractice", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreatePractice200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreatePractice200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreatePractice200Response>() {});
        

        return new ApiResponse<CreatePractice200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createPracticeRequestBuilder(@javax.annotation.Nonnull CreatePracticeRequest createPracticeRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createPracticeRequest' is set
    if (createPracticeRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createPracticeRequest' when calling createPractice");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/practices";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createPracticeRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Read practice
   * Reads a platform-owned practice by id.
   * @param practiceId  (required)
   * @return CreatePractice200Response
   * @throws ApiException if fails to make API call
   */
  public CreatePractice200Response getPractice(@javax.annotation.Nullable String practiceId) throws ApiException {
    return getPractice(practiceId, null);
  }

  /**
   * Read practice
   * Reads a platform-owned practice by id.
   * @param practiceId  (required)
   * @param headers Optional headers to include in the request
   * @return CreatePractice200Response
   * @throws ApiException if fails to make API call
   */
  public CreatePractice200Response getPractice(@javax.annotation.Nullable String practiceId, Map<String, String> headers) throws ApiException {
    ApiResponse<CreatePractice200Response> localVarResponse = getPracticeWithHttpInfo(practiceId, headers);
    return localVarResponse.getData();
  }

  /**
   * Read practice
   * Reads a platform-owned practice by id.
   * @param practiceId  (required)
   * @return ApiResponse&lt;CreatePractice200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreatePractice200Response> getPracticeWithHttpInfo(@javax.annotation.Nullable String practiceId) throws ApiException {
    return getPracticeWithHttpInfo(practiceId, null);
  }

  /**
   * Read practice
   * Reads a platform-owned practice by id.
   * @param practiceId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreatePractice200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreatePractice200Response> getPracticeWithHttpInfo(@javax.annotation.Nullable String practiceId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPracticeRequestBuilder(practiceId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPractice", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreatePractice200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreatePractice200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreatePractice200Response>() {});
        

        return new ApiResponse<CreatePractice200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPracticeRequestBuilder(@javax.annotation.Nullable String practiceId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'practiceId' is set
    if (practiceId == null) {
      throw new ApiException(400, "Missing the required parameter 'practiceId' when calling getPractice");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/practices/{practiceId}"
        .replace("{practiceId}", ApiClient.urlEncode(practiceId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List practices
   * 
   * @return ListPractices200Response
   * @throws ApiException if fails to make API call
   */
  public ListPractices200Response listPractices() throws ApiException {
    return listPractices(null);
  }

  /**
   * List practices
   * 
   * @param headers Optional headers to include in the request
   * @return ListPractices200Response
   * @throws ApiException if fails to make API call
   */
  public ListPractices200Response listPractices(Map<String, String> headers) throws ApiException {
    ApiResponse<ListPractices200Response> localVarResponse = listPracticesWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List practices
   * 
   * @return ApiResponse&lt;ListPractices200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListPractices200Response> listPracticesWithHttpInfo() throws ApiException {
    return listPracticesWithHttpInfo(null);
  }

  /**
   * List practices
   * 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListPractices200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListPractices200Response> listPracticesWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listPracticesRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listPractices", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListPractices200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListPractices200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListPractices200Response>() {});
        

        return new ApiResponse<ListPractices200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listPracticesRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/practices";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update practice
   * Updates a platform-owned practice. Send Idempotency-Key for safe retries.
   * @param practiceId  (required)
   * @return CreatePractice200Response
   * @throws ApiException if fails to make API call
   */
  public CreatePractice200Response updatePractice(@javax.annotation.Nonnull String practiceId) throws ApiException {
    return updatePractice(practiceId, null);
  }

  /**
   * Update practice
   * Updates a platform-owned practice. Send Idempotency-Key for safe retries.
   * @param practiceId  (required)
   * @param headers Optional headers to include in the request
   * @return CreatePractice200Response
   * @throws ApiException if fails to make API call
   */
  public CreatePractice200Response updatePractice(@javax.annotation.Nonnull String practiceId, Map<String, String> headers) throws ApiException {
    ApiResponse<CreatePractice200Response> localVarResponse = updatePracticeWithHttpInfo(practiceId, headers);
    return localVarResponse.getData();
  }

  /**
   * Update practice
   * Updates a platform-owned practice. Send Idempotency-Key for safe retries.
   * @param practiceId  (required)
   * @return ApiResponse&lt;CreatePractice200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreatePractice200Response> updatePracticeWithHttpInfo(@javax.annotation.Nonnull String practiceId) throws ApiException {
    return updatePracticeWithHttpInfo(practiceId, null);
  }

  /**
   * Update practice
   * Updates a platform-owned practice. Send Idempotency-Key for safe retries.
   * @param practiceId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreatePractice200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreatePractice200Response> updatePracticeWithHttpInfo(@javax.annotation.Nonnull String practiceId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updatePracticeRequestBuilder(practiceId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updatePractice", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreatePractice200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreatePractice200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreatePractice200Response>() {});
        

        return new ApiResponse<CreatePractice200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updatePracticeRequestBuilder(@javax.annotation.Nonnull String practiceId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'practiceId' is set
    if (practiceId == null) {
      throw new ApiException(400, "Missing the required parameter 'practiceId' when calling updatePractice");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/practices/{practiceId}"
        .replace("{practiceId}", ApiClient.urlEncode(practiceId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
