/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.api;

import ai.joinaffinity.sdk.ApiException;
import ai.joinaffinity.sdk.model.Error;
import ai.joinaffinity.sdk.model.GetApiAccess200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ApiKeysApi
 */
@Disabled
public class ApiKeysApiTest {

    private final ApiKeysApi api = new ApiKeysApi();

    
    /**
     * Read API key access
     *
     * Returns the authenticated API key subject, mode, and scopes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiAccessTest() throws ApiException {
        GetApiAccess200Response response = 
        api.getApiAccess();
        
        // TODO: test validations
    }
    
}
