/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.api;

import ai.joinaffinity.sdk.ApiException;
import ai.joinaffinity.sdk.model.Error;
import ai.joinaffinity.sdk.model.ListCatalogItems200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for CatalogApi
 */
@Disabled
public class CatalogApiTest {

    private final CatalogApi api = new CatalogApi();

    
    /**
     * List catalog items
     *
     * Searches the Affinity catalog across all connected compounders and routing restrictions.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCatalogItemsTest() throws ApiException {
        String query = null;
        ListCatalogItems200Response response = 
        api.listCatalogItems(query);
        
        // TODO: test validations
    }
    
}
