/*
Affinity API

Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOrderRequestAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrderRequestAnyOf1{}

// CreateOrderRequestAnyOf1 struct for CreateOrderRequestAnyOf1
type CreateOrderRequestAnyOf1 struct {
	PracticeId             NullableString                          `json:"practiceId"`
	ExternalOrderId        string                                  `json:"externalOrderId"`
	PharmacyOrganizationId string                                  `json:"pharmacyOrganizationId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	PrescriptionId         string                                  `json:"prescriptionId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	PrescriptionVersionId  string                                  `json:"prescriptionVersionId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	RegisteredLocationId   string                                  `json:"registeredLocationId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	ShippingAddress        CreateOrderRequestAnyOf1ShippingAddress `json:"shippingAddress"`
}

type _CreateOrderRequestAnyOf1 CreateOrderRequestAnyOf1

// NewCreateOrderRequestAnyOf1 instantiates a new CreateOrderRequestAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestAnyOf1(practiceId NullableString, externalOrderId string, pharmacyOrganizationId string, prescriptionId string, prescriptionVersionId string, registeredLocationId string, shippingAddress CreateOrderRequestAnyOf1ShippingAddress) *CreateOrderRequestAnyOf1 {
	this := CreateOrderRequestAnyOf1{}
	this.PracticeId = practiceId
	this.ExternalOrderId = externalOrderId
	this.PharmacyOrganizationId = pharmacyOrganizationId
	this.PrescriptionId = prescriptionId
	this.PrescriptionVersionId = prescriptionVersionId
	this.RegisteredLocationId = registeredLocationId
	this.ShippingAddress = shippingAddress
	return &this
}

// NewCreateOrderRequestAnyOf1WithDefaults instantiates a new CreateOrderRequestAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestAnyOf1WithDefaults() *CreateOrderRequestAnyOf1 {
	this := CreateOrderRequestAnyOf1{}
	return &this
}

// GetPracticeId returns the PracticeId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateOrderRequestAnyOf1) GetPracticeId() string {
	if o == nil || o.PracticeId.Get() == nil {
		var ret string
		return ret
	}

	return *o.PracticeId.Get()
}

// GetPracticeIdOk returns a tuple with the PracticeId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestAnyOf1) GetPracticeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PracticeId.Get(), o.PracticeId.IsSet()
}

// SetPracticeId sets field value
func (o *CreateOrderRequestAnyOf1) SetPracticeId(v string) {
	o.PracticeId.Set(&v)
}

// GetExternalOrderId returns the ExternalOrderId field value
func (o *CreateOrderRequestAnyOf1) GetExternalOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalOrderId
}

// GetExternalOrderIdOk returns a tuple with the ExternalOrderId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf1) GetExternalOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalOrderId, true
}

// SetExternalOrderId sets field value
func (o *CreateOrderRequestAnyOf1) SetExternalOrderId(v string) {
	o.ExternalOrderId = v
}

// GetPharmacyOrganizationId returns the PharmacyOrganizationId field value
func (o *CreateOrderRequestAnyOf1) GetPharmacyOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PharmacyOrganizationId
}

// GetPharmacyOrganizationIdOk returns a tuple with the PharmacyOrganizationId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf1) GetPharmacyOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PharmacyOrganizationId, true
}

// SetPharmacyOrganizationId sets field value
func (o *CreateOrderRequestAnyOf1) SetPharmacyOrganizationId(v string) {
	o.PharmacyOrganizationId = v
}

// GetPrescriptionId returns the PrescriptionId field value
func (o *CreateOrderRequestAnyOf1) GetPrescriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrescriptionId
}

// GetPrescriptionIdOk returns a tuple with the PrescriptionId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf1) GetPrescriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrescriptionId, true
}

// SetPrescriptionId sets field value
func (o *CreateOrderRequestAnyOf1) SetPrescriptionId(v string) {
	o.PrescriptionId = v
}

// GetPrescriptionVersionId returns the PrescriptionVersionId field value
func (o *CreateOrderRequestAnyOf1) GetPrescriptionVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrescriptionVersionId
}

// GetPrescriptionVersionIdOk returns a tuple with the PrescriptionVersionId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf1) GetPrescriptionVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrescriptionVersionId, true
}

// SetPrescriptionVersionId sets field value
func (o *CreateOrderRequestAnyOf1) SetPrescriptionVersionId(v string) {
	o.PrescriptionVersionId = v
}

// GetRegisteredLocationId returns the RegisteredLocationId field value
func (o *CreateOrderRequestAnyOf1) GetRegisteredLocationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegisteredLocationId
}

// GetRegisteredLocationIdOk returns a tuple with the RegisteredLocationId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf1) GetRegisteredLocationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegisteredLocationId, true
}

// SetRegisteredLocationId sets field value
func (o *CreateOrderRequestAnyOf1) SetRegisteredLocationId(v string) {
	o.RegisteredLocationId = v
}

// GetShippingAddress returns the ShippingAddress field value
func (o *CreateOrderRequestAnyOf1) GetShippingAddress() CreateOrderRequestAnyOf1ShippingAddress {
	if o == nil {
		var ret CreateOrderRequestAnyOf1ShippingAddress
		return ret
	}

	return o.ShippingAddress
}

// GetShippingAddressOk returns a tuple with the ShippingAddress field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf1) GetShippingAddressOk() (*CreateOrderRequestAnyOf1ShippingAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShippingAddress, true
}

// SetShippingAddress sets field value
func (o *CreateOrderRequestAnyOf1) SetShippingAddress(v CreateOrderRequestAnyOf1ShippingAddress) {
	o.ShippingAddress = v
}

func (o CreateOrderRequestAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderRequestAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["practiceId"] = o.PracticeId.Get()
	toSerialize["externalOrderId"] = o.ExternalOrderId
	toSerialize["pharmacyOrganizationId"] = o.PharmacyOrganizationId
	toSerialize["prescriptionId"] = o.PrescriptionId
	toSerialize["prescriptionVersionId"] = o.PrescriptionVersionId
	toSerialize["registeredLocationId"] = o.RegisteredLocationId
	toSerialize["shippingAddress"] = o.ShippingAddress
	return toSerialize, nil
}

func (o *CreateOrderRequestAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"practiceId",
		"externalOrderId",
		"pharmacyOrganizationId",
		"prescriptionId",
		"prescriptionVersionId",
		"registeredLocationId",
		"shippingAddress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrderRequestAnyOf1 := _CreateOrderRequestAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrderRequestAnyOf1)

	if err != nil {
		return err
	}

	*o = CreateOrderRequestAnyOf1(varCreateOrderRequestAnyOf1)

	return err
}

type NullableCreateOrderRequestAnyOf1 struct {
	value *CreateOrderRequestAnyOf1
	isSet bool
}

func (v NullableCreateOrderRequestAnyOf1) Get() *CreateOrderRequestAnyOf1 {
	return v.value
}

func (v *NullableCreateOrderRequestAnyOf1) Set(val *CreateOrderRequestAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestAnyOf1(val *CreateOrderRequestAnyOf1) *NullableCreateOrderRequestAnyOf1 {
	return &NullableCreateOrderRequestAnyOf1{value: val, isSet: true}
}

func (v NullableCreateOrderRequestAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
