/*
Affinity API

Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"encoding/json"
	"fmt"
)

// checks if the ListOrders200ResponseOrdersInnerRouting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOrders200ResponseOrdersInnerRouting{}

// ListOrders200ResponseOrdersInnerRouting struct for ListOrders200ResponseOrdersInnerRouting
type ListOrders200ResponseOrdersInnerRouting struct {
	BlockedReasons         []string       `json:"blockedReasons"`
	CandidateCompounderIds []string       `json:"candidateCompounderIds"`
	ColdShip               bool           `json:"coldShip"`
	SelectedCompounderId   NullableString `json:"selectedCompounderId"`
	AdditionalProperties   map[string]interface{}
}

type _ListOrders200ResponseOrdersInnerRouting ListOrders200ResponseOrdersInnerRouting

// NewListOrders200ResponseOrdersInnerRouting instantiates a new ListOrders200ResponseOrdersInnerRouting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOrders200ResponseOrdersInnerRouting(blockedReasons []string, candidateCompounderIds []string, coldShip bool, selectedCompounderId NullableString) *ListOrders200ResponseOrdersInnerRouting {
	this := ListOrders200ResponseOrdersInnerRouting{}
	this.BlockedReasons = blockedReasons
	this.CandidateCompounderIds = candidateCompounderIds
	this.ColdShip = coldShip
	this.SelectedCompounderId = selectedCompounderId
	return &this
}

// NewListOrders200ResponseOrdersInnerRoutingWithDefaults instantiates a new ListOrders200ResponseOrdersInnerRouting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOrders200ResponseOrdersInnerRoutingWithDefaults() *ListOrders200ResponseOrdersInnerRouting {
	this := ListOrders200ResponseOrdersInnerRouting{}
	return &this
}

// GetBlockedReasons returns the BlockedReasons field value
func (o *ListOrders200ResponseOrdersInnerRouting) GetBlockedReasons() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BlockedReasons
}

// GetBlockedReasonsOk returns a tuple with the BlockedReasons field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseOrdersInnerRouting) GetBlockedReasonsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockedReasons, true
}

// SetBlockedReasons sets field value
func (o *ListOrders200ResponseOrdersInnerRouting) SetBlockedReasons(v []string) {
	o.BlockedReasons = v
}

// GetCandidateCompounderIds returns the CandidateCompounderIds field value
func (o *ListOrders200ResponseOrdersInnerRouting) GetCandidateCompounderIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CandidateCompounderIds
}

// GetCandidateCompounderIdsOk returns a tuple with the CandidateCompounderIds field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseOrdersInnerRouting) GetCandidateCompounderIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CandidateCompounderIds, true
}

// SetCandidateCompounderIds sets field value
func (o *ListOrders200ResponseOrdersInnerRouting) SetCandidateCompounderIds(v []string) {
	o.CandidateCompounderIds = v
}

// GetColdShip returns the ColdShip field value
func (o *ListOrders200ResponseOrdersInnerRouting) GetColdShip() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ColdShip
}

// GetColdShipOk returns a tuple with the ColdShip field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseOrdersInnerRouting) GetColdShipOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ColdShip, true
}

// SetColdShip sets field value
func (o *ListOrders200ResponseOrdersInnerRouting) SetColdShip(v bool) {
	o.ColdShip = v
}

// GetSelectedCompounderId returns the SelectedCompounderId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListOrders200ResponseOrdersInnerRouting) GetSelectedCompounderId() string {
	if o == nil || o.SelectedCompounderId.Get() == nil {
		var ret string
		return ret
	}

	return *o.SelectedCompounderId.Get()
}

// GetSelectedCompounderIdOk returns a tuple with the SelectedCompounderId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrders200ResponseOrdersInnerRouting) GetSelectedCompounderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelectedCompounderId.Get(), o.SelectedCompounderId.IsSet()
}

// SetSelectedCompounderId sets field value
func (o *ListOrders200ResponseOrdersInnerRouting) SetSelectedCompounderId(v string) {
	o.SelectedCompounderId.Set(&v)
}

func (o ListOrders200ResponseOrdersInnerRouting) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOrders200ResponseOrdersInnerRouting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["blockedReasons"] = o.BlockedReasons
	toSerialize["candidateCompounderIds"] = o.CandidateCompounderIds
	toSerialize["coldShip"] = o.ColdShip
	toSerialize["selectedCompounderId"] = o.SelectedCompounderId.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOrders200ResponseOrdersInnerRouting) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"blockedReasons",
		"candidateCompounderIds",
		"coldShip",
		"selectedCompounderId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListOrders200ResponseOrdersInnerRouting := _ListOrders200ResponseOrdersInnerRouting{}

	err = json.Unmarshal(data, &varListOrders200ResponseOrdersInnerRouting)

	if err != nil {
		return err
	}

	*o = ListOrders200ResponseOrdersInnerRouting(varListOrders200ResponseOrdersInnerRouting)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "blockedReasons")
		delete(additionalProperties, "candidateCompounderIds")
		delete(additionalProperties, "coldShip")
		delete(additionalProperties, "selectedCompounderId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOrders200ResponseOrdersInnerRouting struct {
	value *ListOrders200ResponseOrdersInnerRouting
	isSet bool
}

func (v NullableListOrders200ResponseOrdersInnerRouting) Get() *ListOrders200ResponseOrdersInnerRouting {
	return v.value
}

func (v *NullableListOrders200ResponseOrdersInnerRouting) Set(val *ListOrders200ResponseOrdersInnerRouting) {
	v.value = val
	v.isSet = true
}

func (v NullableListOrders200ResponseOrdersInnerRouting) IsSet() bool {
	return v.isSet
}

func (v *NullableListOrders200ResponseOrdersInnerRouting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOrders200ResponseOrdersInnerRouting(val *ListOrders200ResponseOrdersInnerRouting) *NullableListOrders200ResponseOrdersInnerRouting {
	return &NullableListOrders200ResponseOrdersInnerRouting{value: val, isSet: true}
}

func (v NullableListOrders200ResponseOrdersInnerRouting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOrders200ResponseOrdersInnerRouting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
