/*
Affinity API

Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"encoding/json"
	"fmt"
)

// checks if the ListPractices200ResponseDataInnerAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPractices200ResponseDataInnerAddress{}

// ListPractices200ResponseDataInnerAddress struct for ListPractices200ResponseDataInnerAddress
type ListPractices200ResponseDataInnerAddress struct {
	City                 string         `json:"city"`
	Country              NullableString `json:"country,omitempty"`
	Line1                NullableString `json:"line1"`
	Line2                NullableString `json:"line2,omitempty"`
	PostalCode           string         `json:"postalCode"`
	State                NullableString `json:"state"`
	AdditionalProperties map[string]interface{}
}

type _ListPractices200ResponseDataInnerAddress ListPractices200ResponseDataInnerAddress

// NewListPractices200ResponseDataInnerAddress instantiates a new ListPractices200ResponseDataInnerAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPractices200ResponseDataInnerAddress(city string, line1 NullableString, postalCode string, state NullableString) *ListPractices200ResponseDataInnerAddress {
	this := ListPractices200ResponseDataInnerAddress{}
	this.City = city
	this.Line1 = line1
	this.PostalCode = postalCode
	this.State = state
	return &this
}

// NewListPractices200ResponseDataInnerAddressWithDefaults instantiates a new ListPractices200ResponseDataInnerAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPractices200ResponseDataInnerAddressWithDefaults() *ListPractices200ResponseDataInnerAddress {
	this := ListPractices200ResponseDataInnerAddress{}
	return &this
}

// GetCity returns the City field value
func (o *ListPractices200ResponseDataInnerAddress) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *ListPractices200ResponseDataInnerAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *ListPractices200ResponseDataInnerAddress) SetCity(v string) {
	o.City = v
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListPractices200ResponseDataInnerAddress) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListPractices200ResponseDataInnerAddress) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *ListPractices200ResponseDataInnerAddress) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *ListPractices200ResponseDataInnerAddress) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *ListPractices200ResponseDataInnerAddress) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *ListPractices200ResponseDataInnerAddress) UnsetCountry() {
	o.Country.Unset()
}

// GetLine1 returns the Line1 field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListPractices200ResponseDataInnerAddress) GetLine1() string {
	if o == nil || o.Line1.Get() == nil {
		var ret string
		return ret
	}

	return *o.Line1.Get()
}

// GetLine1Ok returns a tuple with the Line1 field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListPractices200ResponseDataInnerAddress) GetLine1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Line1.Get(), o.Line1.IsSet()
}

// SetLine1 sets field value
func (o *ListPractices200ResponseDataInnerAddress) SetLine1(v string) {
	o.Line1.Set(&v)
}

// GetLine2 returns the Line2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListPractices200ResponseDataInnerAddress) GetLine2() string {
	if o == nil || IsNil(o.Line2.Get()) {
		var ret string
		return ret
	}
	return *o.Line2.Get()
}

// GetLine2Ok returns a tuple with the Line2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListPractices200ResponseDataInnerAddress) GetLine2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Line2.Get(), o.Line2.IsSet()
}

// HasLine2 returns a boolean if a field has been set.
func (o *ListPractices200ResponseDataInnerAddress) HasLine2() bool {
	if o != nil && o.Line2.IsSet() {
		return true
	}

	return false
}

// SetLine2 gets a reference to the given NullableString and assigns it to the Line2 field.
func (o *ListPractices200ResponseDataInnerAddress) SetLine2(v string) {
	o.Line2.Set(&v)
}

// SetLine2Nil sets the value for Line2 to be an explicit nil
func (o *ListPractices200ResponseDataInnerAddress) SetLine2Nil() {
	o.Line2.Set(nil)
}

// UnsetLine2 ensures that no value is present for Line2, not even an explicit nil
func (o *ListPractices200ResponseDataInnerAddress) UnsetLine2() {
	o.Line2.Unset()
}

// GetPostalCode returns the PostalCode field value
func (o *ListPractices200ResponseDataInnerAddress) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *ListPractices200ResponseDataInnerAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *ListPractices200ResponseDataInnerAddress) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetState returns the State field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListPractices200ResponseDataInnerAddress) GetState() string {
	if o == nil || o.State.Get() == nil {
		var ret string
		return ret
	}

	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListPractices200ResponseDataInnerAddress) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// SetState sets field value
func (o *ListPractices200ResponseDataInnerAddress) SetState(v string) {
	o.State.Set(&v)
}

func (o ListPractices200ResponseDataInnerAddress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPractices200ResponseDataInnerAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["city"] = o.City
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	toSerialize["line1"] = o.Line1.Get()
	if o.Line2.IsSet() {
		toSerialize["line2"] = o.Line2.Get()
	}
	toSerialize["postalCode"] = o.PostalCode
	toSerialize["state"] = o.State.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListPractices200ResponseDataInnerAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"city",
		"line1",
		"postalCode",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPractices200ResponseDataInnerAddress := _ListPractices200ResponseDataInnerAddress{}

	err = json.Unmarshal(data, &varListPractices200ResponseDataInnerAddress)

	if err != nil {
		return err
	}

	*o = ListPractices200ResponseDataInnerAddress(varListPractices200ResponseDataInnerAddress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "city")
		delete(additionalProperties, "country")
		delete(additionalProperties, "line1")
		delete(additionalProperties, "line2")
		delete(additionalProperties, "postalCode")
		delete(additionalProperties, "state")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListPractices200ResponseDataInnerAddress struct {
	value *ListPractices200ResponseDataInnerAddress
	isSet bool
}

func (v NullableListPractices200ResponseDataInnerAddress) Get() *ListPractices200ResponseDataInnerAddress {
	return v.value
}

func (v *NullableListPractices200ResponseDataInnerAddress) Set(val *ListPractices200ResponseDataInnerAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableListPractices200ResponseDataInnerAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableListPractices200ResponseDataInnerAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPractices200ResponseDataInnerAddress(val *ListPractices200ResponseDataInnerAddress) *NullableListPractices200ResponseDataInnerAddress {
	return &NullableListPractices200ResponseDataInnerAddress{value: val, isSet: true}
}

func (v NullableListPractices200ResponseDataInnerAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPractices200ResponseDataInnerAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
