/*
Affinity API

Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"encoding/json"
	"fmt"
)

// checks if the GetPlatformOrganization200ResponseAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPlatformOrganization200ResponseAccount{}

// GetPlatformOrganization200ResponseAccount struct for GetPlatformOrganization200ResponseAccount
type GetPlatformOrganization200ResponseAccount struct {
	AlertEmails            []string       `json:"alertEmails"`
	AlertIntegrationIssues bool           `json:"alertIntegrationIssues"`
	AlertNewOrders         bool           `json:"alertNewOrders"`
	AlertStatusChanges     bool           `json:"alertStatusChanges"`
	DisplayName            NullableString `json:"displayName"`
	Id                     NullableString `json:"id"`
	OrganizationId         NullableString `json:"organizationId"`
	Slug                   NullableString `json:"slug"`
	SupportEmail           NullableString `json:"supportEmail"`
	WebsiteUrl             NullableString `json:"websiteUrl"`
	AdditionalProperties   map[string]interface{}
}

type _GetPlatformOrganization200ResponseAccount GetPlatformOrganization200ResponseAccount

// NewGetPlatformOrganization200ResponseAccount instantiates a new GetPlatformOrganization200ResponseAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPlatformOrganization200ResponseAccount(alertEmails []string, alertIntegrationIssues bool, alertNewOrders bool, alertStatusChanges bool, displayName NullableString, id NullableString, organizationId NullableString, slug NullableString, supportEmail NullableString, websiteUrl NullableString) *GetPlatformOrganization200ResponseAccount {
	this := GetPlatformOrganization200ResponseAccount{}
	this.AlertEmails = alertEmails
	this.AlertIntegrationIssues = alertIntegrationIssues
	this.AlertNewOrders = alertNewOrders
	this.AlertStatusChanges = alertStatusChanges
	this.DisplayName = displayName
	this.Id = id
	this.OrganizationId = organizationId
	this.Slug = slug
	this.SupportEmail = supportEmail
	this.WebsiteUrl = websiteUrl
	return &this
}

// NewGetPlatformOrganization200ResponseAccountWithDefaults instantiates a new GetPlatformOrganization200ResponseAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPlatformOrganization200ResponseAccountWithDefaults() *GetPlatformOrganization200ResponseAccount {
	this := GetPlatformOrganization200ResponseAccount{}
	return &this
}

// GetAlertEmails returns the AlertEmails field value
func (o *GetPlatformOrganization200ResponseAccount) GetAlertEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AlertEmails
}

// GetAlertEmailsOk returns a tuple with the AlertEmails field value
// and a boolean to check if the value has been set.
func (o *GetPlatformOrganization200ResponseAccount) GetAlertEmailsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AlertEmails, true
}

// SetAlertEmails sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetAlertEmails(v []string) {
	o.AlertEmails = v
}

// GetAlertIntegrationIssues returns the AlertIntegrationIssues field value
func (o *GetPlatformOrganization200ResponseAccount) GetAlertIntegrationIssues() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AlertIntegrationIssues
}

// GetAlertIntegrationIssuesOk returns a tuple with the AlertIntegrationIssues field value
// and a boolean to check if the value has been set.
func (o *GetPlatformOrganization200ResponseAccount) GetAlertIntegrationIssuesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertIntegrationIssues, true
}

// SetAlertIntegrationIssues sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetAlertIntegrationIssues(v bool) {
	o.AlertIntegrationIssues = v
}

// GetAlertNewOrders returns the AlertNewOrders field value
func (o *GetPlatformOrganization200ResponseAccount) GetAlertNewOrders() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AlertNewOrders
}

// GetAlertNewOrdersOk returns a tuple with the AlertNewOrders field value
// and a boolean to check if the value has been set.
func (o *GetPlatformOrganization200ResponseAccount) GetAlertNewOrdersOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertNewOrders, true
}

// SetAlertNewOrders sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetAlertNewOrders(v bool) {
	o.AlertNewOrders = v
}

// GetAlertStatusChanges returns the AlertStatusChanges field value
func (o *GetPlatformOrganization200ResponseAccount) GetAlertStatusChanges() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AlertStatusChanges
}

// GetAlertStatusChangesOk returns a tuple with the AlertStatusChanges field value
// and a boolean to check if the value has been set.
func (o *GetPlatformOrganization200ResponseAccount) GetAlertStatusChangesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertStatusChanges, true
}

// SetAlertStatusChanges sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetAlertStatusChanges(v bool) {
	o.AlertStatusChanges = v
}

// GetDisplayName returns the DisplayName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetDisplayName() string {
	if o == nil || o.DisplayName.Get() == nil {
		var ret string
		return ret
	}

	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// SetDisplayName sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetId(v string) {
	o.Id.Set(&v)
}

// GetOrganizationId returns the OrganizationId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetOrganizationId() string {
	if o == nil || o.OrganizationId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OrganizationId.Get()
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationId.Get(), o.OrganizationId.IsSet()
}

// SetOrganizationId sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetOrganizationId(v string) {
	o.OrganizationId.Set(&v)
}

// GetSlug returns the Slug field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetSlug() string {
	if o == nil || o.Slug.Get() == nil {
		var ret string
		return ret
	}

	return *o.Slug.Get()
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slug.Get(), o.Slug.IsSet()
}

// SetSlug sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetSlug(v string) {
	o.Slug.Set(&v)
}

// GetSupportEmail returns the SupportEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetSupportEmail() string {
	if o == nil || o.SupportEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.SupportEmail.Get()
}

// GetSupportEmailOk returns a tuple with the SupportEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetSupportEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportEmail.Get(), o.SupportEmail.IsSet()
}

// SetSupportEmail sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetSupportEmail(v string) {
	o.SupportEmail.Set(&v)
}

// GetWebsiteUrl returns the WebsiteUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetWebsiteUrl() string {
	if o == nil || o.WebsiteUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.WebsiteUrl.Get()
}

// GetWebsiteUrlOk returns a tuple with the WebsiteUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPlatformOrganization200ResponseAccount) GetWebsiteUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebsiteUrl.Get(), o.WebsiteUrl.IsSet()
}

// SetWebsiteUrl sets field value
func (o *GetPlatformOrganization200ResponseAccount) SetWebsiteUrl(v string) {
	o.WebsiteUrl.Set(&v)
}

func (o GetPlatformOrganization200ResponseAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPlatformOrganization200ResponseAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alertEmails"] = o.AlertEmails
	toSerialize["alertIntegrationIssues"] = o.AlertIntegrationIssues
	toSerialize["alertNewOrders"] = o.AlertNewOrders
	toSerialize["alertStatusChanges"] = o.AlertStatusChanges
	toSerialize["displayName"] = o.DisplayName.Get()
	toSerialize["id"] = o.Id.Get()
	toSerialize["organizationId"] = o.OrganizationId.Get()
	toSerialize["slug"] = o.Slug.Get()
	toSerialize["supportEmail"] = o.SupportEmail.Get()
	toSerialize["websiteUrl"] = o.WebsiteUrl.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetPlatformOrganization200ResponseAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alertEmails",
		"alertIntegrationIssues",
		"alertNewOrders",
		"alertStatusChanges",
		"displayName",
		"id",
		"organizationId",
		"slug",
		"supportEmail",
		"websiteUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPlatformOrganization200ResponseAccount := _GetPlatformOrganization200ResponseAccount{}

	err = json.Unmarshal(data, &varGetPlatformOrganization200ResponseAccount)

	if err != nil {
		return err
	}

	*o = GetPlatformOrganization200ResponseAccount(varGetPlatformOrganization200ResponseAccount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "alertEmails")
		delete(additionalProperties, "alertIntegrationIssues")
		delete(additionalProperties, "alertNewOrders")
		delete(additionalProperties, "alertStatusChanges")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "id")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "supportEmail")
		delete(additionalProperties, "websiteUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetPlatformOrganization200ResponseAccount struct {
	value *GetPlatformOrganization200ResponseAccount
	isSet bool
}

func (v NullableGetPlatformOrganization200ResponseAccount) Get() *GetPlatformOrganization200ResponseAccount {
	return v.value
}

func (v *NullableGetPlatformOrganization200ResponseAccount) Set(val *GetPlatformOrganization200ResponseAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPlatformOrganization200ResponseAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPlatformOrganization200ResponseAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPlatformOrganization200ResponseAccount(val *GetPlatformOrganization200ResponseAccount) *NullableGetPlatformOrganization200ResponseAccount {
	return &NullableGetPlatformOrganization200ResponseAccount{value: val, isSet: true}
}

func (v NullableGetPlatformOrganization200ResponseAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPlatformOrganization200ResponseAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
