/*
Affinity API

Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateOrder200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrder200Response{}

// CreateOrder200Response struct for CreateOrder200Response
type CreateOrder200Response struct {
	Order                CreateOrder200ResponseOrder `json:"order"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrder200Response CreateOrder200Response

// NewCreateOrder200Response instantiates a new CreateOrder200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrder200Response(order CreateOrder200ResponseOrder) *CreateOrder200Response {
	this := CreateOrder200Response{}
	this.Order = order
	return &this
}

// NewCreateOrder200ResponseWithDefaults instantiates a new CreateOrder200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrder200ResponseWithDefaults() *CreateOrder200Response {
	this := CreateOrder200Response{}
	return &this
}

// GetOrder returns the Order field value
func (o *CreateOrder200Response) GetOrder() CreateOrder200ResponseOrder {
	if o == nil {
		var ret CreateOrder200ResponseOrder
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *CreateOrder200Response) GetOrderOk() (*CreateOrder200ResponseOrder, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *CreateOrder200Response) SetOrder(v CreateOrder200ResponseOrder) {
	o.Order = v
}

func (o CreateOrder200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrder200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order"] = o.Order

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrder200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrder200Response := _CreateOrder200Response{}

	err = json.Unmarshal(data, &varCreateOrder200Response)

	if err != nil {
		return err
	}

	*o = CreateOrder200Response(varCreateOrder200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "order")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrder200Response struct {
	value *CreateOrder200Response
	isSet bool
}

func (v NullableCreateOrder200Response) Get() *CreateOrder200Response {
	return v.value
}

func (v *NullableCreateOrder200Response) Set(val *CreateOrder200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrder200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrder200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrder200Response(val *CreateOrder200Response) *NullableCreateOrder200Response {
	return &NullableCreateOrder200Response{value: val, isSet: true}
}

func (v NullableCreateOrder200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrder200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
