/*
Affinity API

Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

API version: 2026-07-19
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetOrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrderResponse{}

// GetOrderResponse struct for GetOrderResponse
type GetOrderResponse struct {
	CancellationReason              NullableString                             `json:"cancellationReason"`
	Carrier                         NullableString                             `json:"carrier"`
	CatalogItemId                   NullableString                             `json:"catalogItemId" validate:"regexp=^cat_[0-9a-hjkmnp-tv-z]{26}$"`
	PracticeId                      string                                     `json:"practiceId" validate:"regexp=^prac_[0-9a-hjkmnp-tv-z]{26}$"`
	CompounderId                    NullableString                             `json:"compounderId" validate:"regexp=^cmp_[0-9a-hjkmnp-tv-z]{26}$"`
	CreatedAt                       string                                     `json:"createdAt"`
	Currency                        string                                     `json:"currency"`
	Directions                      string                                     `json:"directions"`
	DosageForm                      NullableString                             `json:"dosageForm"`
	ExternalOrderId                 string                                     `json:"externalOrderId"`
	ExternalSubmissionAttempted     bool                                       `json:"externalSubmissionAttempted"`
	ExternalSubmissionBlockedReason NullableString                             `json:"externalSubmissionBlockedReason"`
	Id                              string                                     `json:"id" validate:"regexp=^ord_[0-9a-hjkmnp-tv-z]{26}$"`
	Livemode                        bool                                       `json:"livemode"`
	MedicationName                  string                                     `json:"medicationName"`
	PatientExternalId               string                                     `json:"patientExternalId"`
	PatientName                     string                                     `json:"patientName"`
	PatientState                    string                                     `json:"patientState"`
	PrescriberName                  NullableString                             `json:"prescriberName"`
	PrescriberNpi                   NullableString                             `json:"prescriberNpi"`
	Quantity                        float32                                    `json:"quantity"`
	QuoteCents                      NullableFloat32                            `json:"quoteCents"`
	Object                          string                                     `json:"object"`
	ReplacesOrderId                 NullableString                             `json:"replacesOrderId" validate:"regexp=^ord_[0-9a-hjkmnp-tv-z]{26}$"`
	Routing                         NullableListOrdersResponseDataInnerRouting `json:"routing"`
	Status                          string                                     `json:"status"`
	Strength                        NullableString                             `json:"strength"`
	TrackingNumber                  NullableString                             `json:"trackingNumber"`
	ShippedAt                       NullableString                             `json:"shippedAt"`
	DeliveredAt                     NullableString                             `json:"deliveredAt"`
	UpdatedAt                       string                                     `json:"updatedAt"`
}

type _GetOrderResponse GetOrderResponse

// NewGetOrderResponse instantiates a new GetOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrderResponse(cancellationReason NullableString, carrier NullableString, catalogItemId NullableString, practiceId string, compounderId NullableString, createdAt string, currency string, directions string, dosageForm NullableString, externalOrderId string, externalSubmissionAttempted bool, externalSubmissionBlockedReason NullableString, id string, livemode bool, medicationName string, patientExternalId string, patientName string, patientState string, prescriberName NullableString, prescriberNpi NullableString, quantity float32, quoteCents NullableFloat32, object string, replacesOrderId NullableString, routing NullableListOrdersResponseDataInnerRouting, status string, strength NullableString, trackingNumber NullableString, shippedAt NullableString, deliveredAt NullableString, updatedAt string) *GetOrderResponse {
	this := GetOrderResponse{}
	this.CancellationReason = cancellationReason
	this.Carrier = carrier
	this.CatalogItemId = catalogItemId
	this.PracticeId = practiceId
	this.CompounderId = compounderId
	this.CreatedAt = createdAt
	this.Currency = currency
	this.Directions = directions
	this.DosageForm = dosageForm
	this.ExternalOrderId = externalOrderId
	this.ExternalSubmissionAttempted = externalSubmissionAttempted
	this.ExternalSubmissionBlockedReason = externalSubmissionBlockedReason
	this.Id = id
	this.Livemode = livemode
	this.MedicationName = medicationName
	this.PatientExternalId = patientExternalId
	this.PatientName = patientName
	this.PatientState = patientState
	this.PrescriberName = prescriberName
	this.PrescriberNpi = prescriberNpi
	this.Quantity = quantity
	this.QuoteCents = quoteCents
	this.Object = object
	this.ReplacesOrderId = replacesOrderId
	this.Routing = routing
	this.Status = status
	this.Strength = strength
	this.TrackingNumber = trackingNumber
	this.ShippedAt = shippedAt
	this.DeliveredAt = deliveredAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetOrderResponseWithDefaults instantiates a new GetOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrderResponseWithDefaults() *GetOrderResponse {
	this := GetOrderResponse{}
	return &this
}

// GetCancellationReason returns the CancellationReason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetCancellationReason() string {
	if o == nil || o.CancellationReason.Get() == nil {
		var ret string
		return ret
	}

	return *o.CancellationReason.Get()
}

// GetCancellationReasonOk returns a tuple with the CancellationReason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetCancellationReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancellationReason.Get(), o.CancellationReason.IsSet()
}

// SetCancellationReason sets field value
func (o *GetOrderResponse) SetCancellationReason(v string) {
	o.CancellationReason.Set(&v)
}

// GetCarrier returns the Carrier field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetCarrier() string {
	if o == nil || o.Carrier.Get() == nil {
		var ret string
		return ret
	}

	return *o.Carrier.Get()
}

// GetCarrierOk returns a tuple with the Carrier field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetCarrierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Carrier.Get(), o.Carrier.IsSet()
}

// SetCarrier sets field value
func (o *GetOrderResponse) SetCarrier(v string) {
	o.Carrier.Set(&v)
}

// GetCatalogItemId returns the CatalogItemId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetCatalogItemId() string {
	if o == nil || o.CatalogItemId.Get() == nil {
		var ret string
		return ret
	}

	return *o.CatalogItemId.Get()
}

// GetCatalogItemIdOk returns a tuple with the CatalogItemId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetCatalogItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CatalogItemId.Get(), o.CatalogItemId.IsSet()
}

// SetCatalogItemId sets field value
func (o *GetOrderResponse) SetCatalogItemId(v string) {
	o.CatalogItemId.Set(&v)
}

// GetPracticeId returns the PracticeId field value
func (o *GetOrderResponse) GetPracticeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PracticeId
}

// GetPracticeIdOk returns a tuple with the PracticeId field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetPracticeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PracticeId, true
}

// SetPracticeId sets field value
func (o *GetOrderResponse) SetPracticeId(v string) {
	o.PracticeId = v
}

// GetCompounderId returns the CompounderId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetCompounderId() string {
	if o == nil || o.CompounderId.Get() == nil {
		var ret string
		return ret
	}

	return *o.CompounderId.Get()
}

// GetCompounderIdOk returns a tuple with the CompounderId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetCompounderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompounderId.Get(), o.CompounderId.IsSet()
}

// SetCompounderId sets field value
func (o *GetOrderResponse) SetCompounderId(v string) {
	o.CompounderId.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetOrderResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetOrderResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCurrency returns the Currency field value
func (o *GetOrderResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *GetOrderResponse) SetCurrency(v string) {
	o.Currency = v
}

// GetDirections returns the Directions field value
func (o *GetOrderResponse) GetDirections() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Directions
}

// GetDirectionsOk returns a tuple with the Directions field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetDirectionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Directions, true
}

// SetDirections sets field value
func (o *GetOrderResponse) SetDirections(v string) {
	o.Directions = v
}

// GetDosageForm returns the DosageForm field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetDosageForm() string {
	if o == nil || o.DosageForm.Get() == nil {
		var ret string
		return ret
	}

	return *o.DosageForm.Get()
}

// GetDosageFormOk returns a tuple with the DosageForm field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetDosageFormOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DosageForm.Get(), o.DosageForm.IsSet()
}

// SetDosageForm sets field value
func (o *GetOrderResponse) SetDosageForm(v string) {
	o.DosageForm.Set(&v)
}

// GetExternalOrderId returns the ExternalOrderId field value
func (o *GetOrderResponse) GetExternalOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalOrderId
}

// GetExternalOrderIdOk returns a tuple with the ExternalOrderId field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetExternalOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalOrderId, true
}

// SetExternalOrderId sets field value
func (o *GetOrderResponse) SetExternalOrderId(v string) {
	o.ExternalOrderId = v
}

// GetExternalSubmissionAttempted returns the ExternalSubmissionAttempted field value
func (o *GetOrderResponse) GetExternalSubmissionAttempted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ExternalSubmissionAttempted
}

// GetExternalSubmissionAttemptedOk returns a tuple with the ExternalSubmissionAttempted field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetExternalSubmissionAttemptedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalSubmissionAttempted, true
}

// SetExternalSubmissionAttempted sets field value
func (o *GetOrderResponse) SetExternalSubmissionAttempted(v bool) {
	o.ExternalSubmissionAttempted = v
}

// GetExternalSubmissionBlockedReason returns the ExternalSubmissionBlockedReason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetExternalSubmissionBlockedReason() string {
	if o == nil || o.ExternalSubmissionBlockedReason.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExternalSubmissionBlockedReason.Get()
}

// GetExternalSubmissionBlockedReasonOk returns a tuple with the ExternalSubmissionBlockedReason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetExternalSubmissionBlockedReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalSubmissionBlockedReason.Get(), o.ExternalSubmissionBlockedReason.IsSet()
}

// SetExternalSubmissionBlockedReason sets field value
func (o *GetOrderResponse) SetExternalSubmissionBlockedReason(v string) {
	o.ExternalSubmissionBlockedReason.Set(&v)
}

// GetId returns the Id field value
func (o *GetOrderResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetOrderResponse) SetId(v string) {
	o.Id = v
}

// GetLivemode returns the Livemode field value
func (o *GetOrderResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *GetOrderResponse) SetLivemode(v bool) {
	o.Livemode = v
}

// GetMedicationName returns the MedicationName field value
func (o *GetOrderResponse) GetMedicationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MedicationName
}

// GetMedicationNameOk returns a tuple with the MedicationName field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetMedicationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MedicationName, true
}

// SetMedicationName sets field value
func (o *GetOrderResponse) SetMedicationName(v string) {
	o.MedicationName = v
}

// GetPatientExternalId returns the PatientExternalId field value
func (o *GetOrderResponse) GetPatientExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PatientExternalId
}

// GetPatientExternalIdOk returns a tuple with the PatientExternalId field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetPatientExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PatientExternalId, true
}

// SetPatientExternalId sets field value
func (o *GetOrderResponse) SetPatientExternalId(v string) {
	o.PatientExternalId = v
}

// GetPatientName returns the PatientName field value
func (o *GetOrderResponse) GetPatientName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PatientName
}

// GetPatientNameOk returns a tuple with the PatientName field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetPatientNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PatientName, true
}

// SetPatientName sets field value
func (o *GetOrderResponse) SetPatientName(v string) {
	o.PatientName = v
}

// GetPatientState returns the PatientState field value
func (o *GetOrderResponse) GetPatientState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PatientState
}

// GetPatientStateOk returns a tuple with the PatientState field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetPatientStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PatientState, true
}

// SetPatientState sets field value
func (o *GetOrderResponse) SetPatientState(v string) {
	o.PatientState = v
}

// GetPrescriberName returns the PrescriberName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetPrescriberName() string {
	if o == nil || o.PrescriberName.Get() == nil {
		var ret string
		return ret
	}

	return *o.PrescriberName.Get()
}

// GetPrescriberNameOk returns a tuple with the PrescriberName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetPrescriberNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrescriberName.Get(), o.PrescriberName.IsSet()
}

// SetPrescriberName sets field value
func (o *GetOrderResponse) SetPrescriberName(v string) {
	o.PrescriberName.Set(&v)
}

// GetPrescriberNpi returns the PrescriberNpi field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetPrescriberNpi() string {
	if o == nil || o.PrescriberNpi.Get() == nil {
		var ret string
		return ret
	}

	return *o.PrescriberNpi.Get()
}

// GetPrescriberNpiOk returns a tuple with the PrescriberNpi field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetPrescriberNpiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrescriberNpi.Get(), o.PrescriberNpi.IsSet()
}

// SetPrescriberNpi sets field value
func (o *GetOrderResponse) SetPrescriberNpi(v string) {
	o.PrescriberNpi.Set(&v)
}

// GetQuantity returns the Quantity field value
func (o *GetOrderResponse) GetQuantity() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetQuantityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *GetOrderResponse) SetQuantity(v float32) {
	o.Quantity = v
}

// GetQuoteCents returns the QuoteCents field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *GetOrderResponse) GetQuoteCents() float32 {
	if o == nil || o.QuoteCents.Get() == nil {
		var ret float32
		return ret
	}

	return *o.QuoteCents.Get()
}

// GetQuoteCentsOk returns a tuple with the QuoteCents field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetQuoteCentsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.QuoteCents.Get(), o.QuoteCents.IsSet()
}

// SetQuoteCents sets field value
func (o *GetOrderResponse) SetQuoteCents(v float32) {
	o.QuoteCents.Set(&v)
}

// GetObject returns the Object field value
func (o *GetOrderResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *GetOrderResponse) SetObject(v string) {
	o.Object = v
}

// GetReplacesOrderId returns the ReplacesOrderId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetReplacesOrderId() string {
	if o == nil || o.ReplacesOrderId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ReplacesOrderId.Get()
}

// GetReplacesOrderIdOk returns a tuple with the ReplacesOrderId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetReplacesOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReplacesOrderId.Get(), o.ReplacesOrderId.IsSet()
}

// SetReplacesOrderId sets field value
func (o *GetOrderResponse) SetReplacesOrderId(v string) {
	o.ReplacesOrderId.Set(&v)
}

// GetRouting returns the Routing field value
// If the value is explicit nil, the zero value for ListOrdersResponseDataInnerRouting will be returned
func (o *GetOrderResponse) GetRouting() ListOrdersResponseDataInnerRouting {
	if o == nil || o.Routing.Get() == nil {
		var ret ListOrdersResponseDataInnerRouting
		return ret
	}

	return *o.Routing.Get()
}

// GetRoutingOk returns a tuple with the Routing field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetRoutingOk() (*ListOrdersResponseDataInnerRouting, bool) {
	if o == nil {
		return nil, false
	}
	return o.Routing.Get(), o.Routing.IsSet()
}

// SetRouting sets field value
func (o *GetOrderResponse) SetRouting(v ListOrdersResponseDataInnerRouting) {
	o.Routing.Set(&v)
}

// GetStatus returns the Status field value
func (o *GetOrderResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetOrderResponse) SetStatus(v string) {
	o.Status = v
}

// GetStrength returns the Strength field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetStrength() string {
	if o == nil || o.Strength.Get() == nil {
		var ret string
		return ret
	}

	return *o.Strength.Get()
}

// GetStrengthOk returns a tuple with the Strength field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetStrengthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Strength.Get(), o.Strength.IsSet()
}

// SetStrength sets field value
func (o *GetOrderResponse) SetStrength(v string) {
	o.Strength.Set(&v)
}

// GetTrackingNumber returns the TrackingNumber field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetTrackingNumber() string {
	if o == nil || o.TrackingNumber.Get() == nil {
		var ret string
		return ret
	}

	return *o.TrackingNumber.Get()
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetTrackingNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrackingNumber.Get(), o.TrackingNumber.IsSet()
}

// SetTrackingNumber sets field value
func (o *GetOrderResponse) SetTrackingNumber(v string) {
	o.TrackingNumber.Set(&v)
}

// GetShippedAt returns the ShippedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetShippedAt() string {
	if o == nil || o.ShippedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.ShippedAt.Get()
}

// GetShippedAtOk returns a tuple with the ShippedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetShippedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShippedAt.Get(), o.ShippedAt.IsSet()
}

// SetShippedAt sets field value
func (o *GetOrderResponse) SetShippedAt(v string) {
	o.ShippedAt.Set(&v)
}

// GetDeliveredAt returns the DeliveredAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetOrderResponse) GetDeliveredAt() string {
	if o == nil || o.DeliveredAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeliveredAt.Get()
}

// GetDeliveredAtOk returns a tuple with the DeliveredAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrderResponse) GetDeliveredAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeliveredAt.Get(), o.DeliveredAt.IsSet()
}

// SetDeliveredAt sets field value
func (o *GetOrderResponse) SetDeliveredAt(v string) {
	o.DeliveredAt.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetOrderResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetOrderResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetOrderResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o GetOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cancellationReason"] = o.CancellationReason.Get()
	toSerialize["carrier"] = o.Carrier.Get()
	toSerialize["catalogItemId"] = o.CatalogItemId.Get()
	toSerialize["practiceId"] = o.PracticeId
	toSerialize["compounderId"] = o.CompounderId.Get()
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["currency"] = o.Currency
	toSerialize["directions"] = o.Directions
	toSerialize["dosageForm"] = o.DosageForm.Get()
	toSerialize["externalOrderId"] = o.ExternalOrderId
	toSerialize["externalSubmissionAttempted"] = o.ExternalSubmissionAttempted
	toSerialize["externalSubmissionBlockedReason"] = o.ExternalSubmissionBlockedReason.Get()
	toSerialize["id"] = o.Id
	toSerialize["livemode"] = o.Livemode
	toSerialize["medicationName"] = o.MedicationName
	toSerialize["patientExternalId"] = o.PatientExternalId
	toSerialize["patientName"] = o.PatientName
	toSerialize["patientState"] = o.PatientState
	toSerialize["prescriberName"] = o.PrescriberName.Get()
	toSerialize["prescriberNpi"] = o.PrescriberNpi.Get()
	toSerialize["quantity"] = o.Quantity
	toSerialize["quoteCents"] = o.QuoteCents.Get()
	toSerialize["object"] = o.Object
	toSerialize["replacesOrderId"] = o.ReplacesOrderId.Get()
	toSerialize["routing"] = o.Routing.Get()
	toSerialize["status"] = o.Status
	toSerialize["strength"] = o.Strength.Get()
	toSerialize["trackingNumber"] = o.TrackingNumber.Get()
	toSerialize["shippedAt"] = o.ShippedAt.Get()
	toSerialize["deliveredAt"] = o.DeliveredAt.Get()
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *GetOrderResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cancellationReason",
		"carrier",
		"catalogItemId",
		"practiceId",
		"compounderId",
		"createdAt",
		"currency",
		"directions",
		"dosageForm",
		"externalOrderId",
		"externalSubmissionAttempted",
		"externalSubmissionBlockedReason",
		"id",
		"livemode",
		"medicationName",
		"patientExternalId",
		"patientName",
		"patientState",
		"prescriberName",
		"prescriberNpi",
		"quantity",
		"quoteCents",
		"object",
		"replacesOrderId",
		"routing",
		"status",
		"strength",
		"trackingNumber",
		"shippedAt",
		"deliveredAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetOrderResponse := _GetOrderResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetOrderResponse)

	if err != nil {
		return err
	}

	*o = GetOrderResponse(varGetOrderResponse)

	return err
}

type NullableGetOrderResponse struct {
	value *GetOrderResponse
	isSet bool
}

func (v NullableGetOrderResponse) Get() *GetOrderResponse {
	return v.value
}

func (v *NullableGetOrderResponse) Set(val *GetOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrderResponse(val *GetOrderResponse) *NullableGetOrderResponse {
	return &NullableGetOrderResponse{value: val, isSet: true}
}

func (v NullableGetOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
