/*
Affinity API

Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"encoding/json"
	"fmt"
)

// checks if the GetWebhookEvent200ResponseAttemptsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWebhookEvent200ResponseAttemptsInner{}

// GetWebhookEvent200ResponseAttemptsInner struct for GetWebhookEvent200ResponseAttemptsInner
type GetWebhookEvent200ResponseAttemptsInner struct {
	AttemptedAt          NullableString  `json:"attemptedAt"`
	ErrorMessage         NullableString  `json:"errorMessage"`
	Id                   NullableString  `json:"id"`
	ResponseBody         NullableString  `json:"responseBody"`
	ResponseStatus       NullableFloat32 `json:"responseStatus"`
	Success              bool            `json:"success"`
	AdditionalProperties map[string]interface{}
}

type _GetWebhookEvent200ResponseAttemptsInner GetWebhookEvent200ResponseAttemptsInner

// NewGetWebhookEvent200ResponseAttemptsInner instantiates a new GetWebhookEvent200ResponseAttemptsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWebhookEvent200ResponseAttemptsInner(attemptedAt NullableString, errorMessage NullableString, id NullableString, responseBody NullableString, responseStatus NullableFloat32, success bool) *GetWebhookEvent200ResponseAttemptsInner {
	this := GetWebhookEvent200ResponseAttemptsInner{}
	this.AttemptedAt = attemptedAt
	this.ErrorMessage = errorMessage
	this.Id = id
	this.ResponseBody = responseBody
	this.ResponseStatus = responseStatus
	this.Success = success
	return &this
}

// NewGetWebhookEvent200ResponseAttemptsInnerWithDefaults instantiates a new GetWebhookEvent200ResponseAttemptsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWebhookEvent200ResponseAttemptsInnerWithDefaults() *GetWebhookEvent200ResponseAttemptsInner {
	this := GetWebhookEvent200ResponseAttemptsInner{}
	return &this
}

// GetAttemptedAt returns the AttemptedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetAttemptedAt() string {
	if o == nil || o.AttemptedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.AttemptedAt.Get()
}

// GetAttemptedAtOk returns a tuple with the AttemptedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetAttemptedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AttemptedAt.Get(), o.AttemptedAt.IsSet()
}

// SetAttemptedAt sets field value
func (o *GetWebhookEvent200ResponseAttemptsInner) SetAttemptedAt(v string) {
	o.AttemptedAt.Set(&v)
}

// GetErrorMessage returns the ErrorMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetErrorMessage() string {
	if o == nil || o.ErrorMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// SetErrorMessage sets field value
func (o *GetWebhookEvent200ResponseAttemptsInner) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *GetWebhookEvent200ResponseAttemptsInner) SetId(v string) {
	o.Id.Set(&v)
}

// GetResponseBody returns the ResponseBody field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetResponseBody() string {
	if o == nil || o.ResponseBody.Get() == nil {
		var ret string
		return ret
	}

	return *o.ResponseBody.Get()
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetResponseBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResponseBody.Get(), o.ResponseBody.IsSet()
}

// SetResponseBody sets field value
func (o *GetWebhookEvent200ResponseAttemptsInner) SetResponseBody(v string) {
	o.ResponseBody.Set(&v)
}

// GetResponseStatus returns the ResponseStatus field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetResponseStatus() float32 {
	if o == nil || o.ResponseStatus.Get() == nil {
		var ret float32
		return ret
	}

	return *o.ResponseStatus.Get()
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWebhookEvent200ResponseAttemptsInner) GetResponseStatusOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResponseStatus.Get(), o.ResponseStatus.IsSet()
}

// SetResponseStatus sets field value
func (o *GetWebhookEvent200ResponseAttemptsInner) SetResponseStatus(v float32) {
	o.ResponseStatus.Set(&v)
}

// GetSuccess returns the Success field value
func (o *GetWebhookEvent200ResponseAttemptsInner) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *GetWebhookEvent200ResponseAttemptsInner) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *GetWebhookEvent200ResponseAttemptsInner) SetSuccess(v bool) {
	o.Success = v
}

func (o GetWebhookEvent200ResponseAttemptsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWebhookEvent200ResponseAttemptsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attemptedAt"] = o.AttemptedAt.Get()
	toSerialize["errorMessage"] = o.ErrorMessage.Get()
	toSerialize["id"] = o.Id.Get()
	toSerialize["responseBody"] = o.ResponseBody.Get()
	toSerialize["responseStatus"] = o.ResponseStatus.Get()
	toSerialize["success"] = o.Success

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetWebhookEvent200ResponseAttemptsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attemptedAt",
		"errorMessage",
		"id",
		"responseBody",
		"responseStatus",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetWebhookEvent200ResponseAttemptsInner := _GetWebhookEvent200ResponseAttemptsInner{}

	err = json.Unmarshal(data, &varGetWebhookEvent200ResponseAttemptsInner)

	if err != nil {
		return err
	}

	*o = GetWebhookEvent200ResponseAttemptsInner(varGetWebhookEvent200ResponseAttemptsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attemptedAt")
		delete(additionalProperties, "errorMessage")
		delete(additionalProperties, "id")
		delete(additionalProperties, "responseBody")
		delete(additionalProperties, "responseStatus")
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetWebhookEvent200ResponseAttemptsInner struct {
	value *GetWebhookEvent200ResponseAttemptsInner
	isSet bool
}

func (v NullableGetWebhookEvent200ResponseAttemptsInner) Get() *GetWebhookEvent200ResponseAttemptsInner {
	return v.value
}

func (v *NullableGetWebhookEvent200ResponseAttemptsInner) Set(val *GetWebhookEvent200ResponseAttemptsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWebhookEvent200ResponseAttemptsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWebhookEvent200ResponseAttemptsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWebhookEvent200ResponseAttemptsInner(val *GetWebhookEvent200ResponseAttemptsInner) *NullableGetWebhookEvent200ResponseAttemptsInner {
	return &NullableGetWebhookEvent200ResponseAttemptsInner{value: val, isSet: true}
}

func (v NullableGetWebhookEvent200ResponseAttemptsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWebhookEvent200ResponseAttemptsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
