/*
Affinity API

Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

API version: 2026-07-19
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateWebhookEndpointRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateWebhookEndpointRequest{}

// UpdateWebhookEndpointRequest struct for UpdateWebhookEndpointRequest
type UpdateWebhookEndpointRequest struct {
	EnabledEvents []string `json:"enabledEvents"`
}

type _UpdateWebhookEndpointRequest UpdateWebhookEndpointRequest

// NewUpdateWebhookEndpointRequest instantiates a new UpdateWebhookEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateWebhookEndpointRequest(enabledEvents []string) *UpdateWebhookEndpointRequest {
	this := UpdateWebhookEndpointRequest{}
	this.EnabledEvents = enabledEvents
	return &this
}

// NewUpdateWebhookEndpointRequestWithDefaults instantiates a new UpdateWebhookEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateWebhookEndpointRequestWithDefaults() *UpdateWebhookEndpointRequest {
	this := UpdateWebhookEndpointRequest{}
	return &this
}

// GetEnabledEvents returns the EnabledEvents field value
func (o *UpdateWebhookEndpointRequest) GetEnabledEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.EnabledEvents
}

// GetEnabledEventsOk returns a tuple with the EnabledEvents field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointRequest) GetEnabledEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnabledEvents, true
}

// SetEnabledEvents sets field value
func (o *UpdateWebhookEndpointRequest) SetEnabledEvents(v []string) {
	o.EnabledEvents = v
}

func (o UpdateWebhookEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateWebhookEndpointRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabledEvents"] = o.EnabledEvents
	return toSerialize, nil
}

func (o *UpdateWebhookEndpointRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabledEvents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateWebhookEndpointRequest := _UpdateWebhookEndpointRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateWebhookEndpointRequest)

	if err != nil {
		return err
	}

	*o = UpdateWebhookEndpointRequest(varUpdateWebhookEndpointRequest)

	return err
}

type NullableUpdateWebhookEndpointRequest struct {
	value *UpdateWebhookEndpointRequest
	isSet bool
}

func (v NullableUpdateWebhookEndpointRequest) Get() *UpdateWebhookEndpointRequest {
	return v.value
}

func (v *NullableUpdateWebhookEndpointRequest) Set(val *UpdateWebhookEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateWebhookEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateWebhookEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateWebhookEndpointRequest(val *UpdateWebhookEndpointRequest) *NullableUpdateWebhookEndpointRequest {
	return &NullableUpdateWebhookEndpointRequest{value: val, isSet: true}
}

func (v NullableUpdateWebhookEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateWebhookEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
