/*
Affinity API

Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"encoding/json"
	"fmt"
)

// checks if the ListWebhookEndpoints200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWebhookEndpoints200Response{}

// ListWebhookEndpoints200Response struct for ListWebhookEndpoints200Response
type ListWebhookEndpoints200Response struct {
	Endpoints            []ListWebhookEndpoints200ResponseEndpointsInner `json:"endpoints"`
	AdditionalProperties map[string]interface{}
}

type _ListWebhookEndpoints200Response ListWebhookEndpoints200Response

// NewListWebhookEndpoints200Response instantiates a new ListWebhookEndpoints200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWebhookEndpoints200Response(endpoints []ListWebhookEndpoints200ResponseEndpointsInner) *ListWebhookEndpoints200Response {
	this := ListWebhookEndpoints200Response{}
	this.Endpoints = endpoints
	return &this
}

// NewListWebhookEndpoints200ResponseWithDefaults instantiates a new ListWebhookEndpoints200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWebhookEndpoints200ResponseWithDefaults() *ListWebhookEndpoints200Response {
	this := ListWebhookEndpoints200Response{}
	return &this
}

// GetEndpoints returns the Endpoints field value
func (o *ListWebhookEndpoints200Response) GetEndpoints() []ListWebhookEndpoints200ResponseEndpointsInner {
	if o == nil {
		var ret []ListWebhookEndpoints200ResponseEndpointsInner
		return ret
	}

	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value
// and a boolean to check if the value has been set.
func (o *ListWebhookEndpoints200Response) GetEndpointsOk() ([]ListWebhookEndpoints200ResponseEndpointsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoints, true
}

// SetEndpoints sets field value
func (o *ListWebhookEndpoints200Response) SetEndpoints(v []ListWebhookEndpoints200ResponseEndpointsInner) {
	o.Endpoints = v
}

func (o ListWebhookEndpoints200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWebhookEndpoints200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoints"] = o.Endpoints

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListWebhookEndpoints200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoints",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListWebhookEndpoints200Response := _ListWebhookEndpoints200Response{}

	err = json.Unmarshal(data, &varListWebhookEndpoints200Response)

	if err != nil {
		return err
	}

	*o = ListWebhookEndpoints200Response(varListWebhookEndpoints200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "endpoints")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListWebhookEndpoints200Response struct {
	value *ListWebhookEndpoints200Response
	isSet bool
}

func (v NullableListWebhookEndpoints200Response) Get() *ListWebhookEndpoints200Response {
	return v.value
}

func (v *NullableListWebhookEndpoints200Response) Set(val *ListWebhookEndpoints200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListWebhookEndpoints200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListWebhookEndpoints200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWebhookEndpoints200Response(val *ListWebhookEndpoints200Response) *NullableListWebhookEndpoints200Response {
	return &NullableListWebhookEndpoints200Response{value: val, isSet: true}
}

func (v NullableListWebhookEndpoints200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWebhookEndpoints200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
