/*
Affinity API

Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOrderRequestAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrderRequestAnyOf{}

// CreateOrderRequestAnyOf struct for CreateOrderRequestAnyOf
type CreateOrderRequestAnyOf struct {
	CatalogItemId   string                              `json:"catalogItemId"`
	PracticeId      string                              `json:"practiceId"`
	Directions      string                              `json:"directions"`
	ExternalOrderId string                              `json:"externalOrderId"`
	Patient         CreateOrderRequestAnyOfPatient      `json:"patient"`
	Prescriber      CreateOrderRequestAnyOfPrescriber   `json:"prescriber"`
	Prescription    CreateOrderRequestAnyOfPrescription `json:"prescription"`
	Quantity        *int32                              `json:"quantity,omitempty"`
	ReplacesOrderId *string                             `json:"replacesOrderId,omitempty" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
}

type _CreateOrderRequestAnyOf CreateOrderRequestAnyOf

// NewCreateOrderRequestAnyOf instantiates a new CreateOrderRequestAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestAnyOf(catalogItemId string, practiceId string, directions string, externalOrderId string, patient CreateOrderRequestAnyOfPatient, prescriber CreateOrderRequestAnyOfPrescriber, prescription CreateOrderRequestAnyOfPrescription) *CreateOrderRequestAnyOf {
	this := CreateOrderRequestAnyOf{}
	this.CatalogItemId = catalogItemId
	this.PracticeId = practiceId
	this.Directions = directions
	this.ExternalOrderId = externalOrderId
	this.Patient = patient
	this.Prescriber = prescriber
	this.Prescription = prescription
	var quantity int32 = 1
	this.Quantity = &quantity
	return &this
}

// NewCreateOrderRequestAnyOfWithDefaults instantiates a new CreateOrderRequestAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestAnyOfWithDefaults() *CreateOrderRequestAnyOf {
	this := CreateOrderRequestAnyOf{}
	var quantity int32 = 1
	this.Quantity = &quantity
	return &this
}

// GetCatalogItemId returns the CatalogItemId field value
func (o *CreateOrderRequestAnyOf) GetCatalogItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CatalogItemId
}

// GetCatalogItemIdOk returns a tuple with the CatalogItemId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetCatalogItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CatalogItemId, true
}

// SetCatalogItemId sets field value
func (o *CreateOrderRequestAnyOf) SetCatalogItemId(v string) {
	o.CatalogItemId = v
}

// GetPracticeId returns the PracticeId field value
func (o *CreateOrderRequestAnyOf) GetPracticeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PracticeId
}

// GetPracticeIdOk returns a tuple with the PracticeId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetPracticeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PracticeId, true
}

// SetPracticeId sets field value
func (o *CreateOrderRequestAnyOf) SetPracticeId(v string) {
	o.PracticeId = v
}

// GetDirections returns the Directions field value
func (o *CreateOrderRequestAnyOf) GetDirections() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Directions
}

// GetDirectionsOk returns a tuple with the Directions field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetDirectionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Directions, true
}

// SetDirections sets field value
func (o *CreateOrderRequestAnyOf) SetDirections(v string) {
	o.Directions = v
}

// GetExternalOrderId returns the ExternalOrderId field value
func (o *CreateOrderRequestAnyOf) GetExternalOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalOrderId
}

// GetExternalOrderIdOk returns a tuple with the ExternalOrderId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetExternalOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalOrderId, true
}

// SetExternalOrderId sets field value
func (o *CreateOrderRequestAnyOf) SetExternalOrderId(v string) {
	o.ExternalOrderId = v
}

// GetPatient returns the Patient field value
func (o *CreateOrderRequestAnyOf) GetPatient() CreateOrderRequestAnyOfPatient {
	if o == nil {
		var ret CreateOrderRequestAnyOfPatient
		return ret
	}

	return o.Patient
}

// GetPatientOk returns a tuple with the Patient field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetPatientOk() (*CreateOrderRequestAnyOfPatient, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Patient, true
}

// SetPatient sets field value
func (o *CreateOrderRequestAnyOf) SetPatient(v CreateOrderRequestAnyOfPatient) {
	o.Patient = v
}

// GetPrescriber returns the Prescriber field value
func (o *CreateOrderRequestAnyOf) GetPrescriber() CreateOrderRequestAnyOfPrescriber {
	if o == nil {
		var ret CreateOrderRequestAnyOfPrescriber
		return ret
	}

	return o.Prescriber
}

// GetPrescriberOk returns a tuple with the Prescriber field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetPrescriberOk() (*CreateOrderRequestAnyOfPrescriber, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prescriber, true
}

// SetPrescriber sets field value
func (o *CreateOrderRequestAnyOf) SetPrescriber(v CreateOrderRequestAnyOfPrescriber) {
	o.Prescriber = v
}

// GetPrescription returns the Prescription field value
func (o *CreateOrderRequestAnyOf) GetPrescription() CreateOrderRequestAnyOfPrescription {
	if o == nil {
		var ret CreateOrderRequestAnyOfPrescription
		return ret
	}

	return o.Prescription
}

// GetPrescriptionOk returns a tuple with the Prescription field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetPrescriptionOk() (*CreateOrderRequestAnyOfPrescription, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prescription, true
}

// SetPrescription sets field value
func (o *CreateOrderRequestAnyOf) SetPrescription(v CreateOrderRequestAnyOfPrescription) {
	o.Prescription = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *CreateOrderRequestAnyOf) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *CreateOrderRequestAnyOf) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *CreateOrderRequestAnyOf) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetReplacesOrderId returns the ReplacesOrderId field value if set, zero value otherwise.
func (o *CreateOrderRequestAnyOf) GetReplacesOrderId() string {
	if o == nil || IsNil(o.ReplacesOrderId) {
		var ret string
		return ret
	}
	return *o.ReplacesOrderId
}

// GetReplacesOrderIdOk returns a tuple with the ReplacesOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOf) GetReplacesOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReplacesOrderId) {
		return nil, false
	}
	return o.ReplacesOrderId, true
}

// HasReplacesOrderId returns a boolean if a field has been set.
func (o *CreateOrderRequestAnyOf) HasReplacesOrderId() bool {
	if o != nil && !IsNil(o.ReplacesOrderId) {
		return true
	}

	return false
}

// SetReplacesOrderId gets a reference to the given string and assigns it to the ReplacesOrderId field.
func (o *CreateOrderRequestAnyOf) SetReplacesOrderId(v string) {
	o.ReplacesOrderId = &v
}

func (o CreateOrderRequestAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderRequestAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["catalogItemId"] = o.CatalogItemId
	toSerialize["practiceId"] = o.PracticeId
	toSerialize["directions"] = o.Directions
	toSerialize["externalOrderId"] = o.ExternalOrderId
	toSerialize["patient"] = o.Patient
	toSerialize["prescriber"] = o.Prescriber
	toSerialize["prescription"] = o.Prescription
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.ReplacesOrderId) {
		toSerialize["replacesOrderId"] = o.ReplacesOrderId
	}
	return toSerialize, nil
}

func (o *CreateOrderRequestAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"catalogItemId",
		"practiceId",
		"directions",
		"externalOrderId",
		"patient",
		"prescriber",
		"prescription",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrderRequestAnyOf := _CreateOrderRequestAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrderRequestAnyOf)

	if err != nil {
		return err
	}

	*o = CreateOrderRequestAnyOf(varCreateOrderRequestAnyOf)

	return err
}

type NullableCreateOrderRequestAnyOf struct {
	value *CreateOrderRequestAnyOf
	isSet bool
}

func (v NullableCreateOrderRequestAnyOf) Get() *CreateOrderRequestAnyOf {
	return v.value
}

func (v *NullableCreateOrderRequestAnyOf) Set(val *CreateOrderRequestAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestAnyOf(val *CreateOrderRequestAnyOf) *NullableCreateOrderRequestAnyOf {
	return &NullableCreateOrderRequestAnyOf{value: val, isSet: true}
}

func (v NullableCreateOrderRequestAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
