/*
Affinity API

Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOrderRequestAnyOfPatientAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrderRequestAnyOfPatientAddress{}

// CreateOrderRequestAnyOfPatientAddress struct for CreateOrderRequestAnyOfPatientAddress
type CreateOrderRequestAnyOfPatientAddress struct {
	City       string         `json:"city"`
	Country    *string        `json:"country,omitempty"`
	Line1      string         `json:"line1"`
	Line2      NullableString `json:"line2,omitempty"`
	PostalCode string         `json:"postalCode"`
	State      string         `json:"state"`
}

type _CreateOrderRequestAnyOfPatientAddress CreateOrderRequestAnyOfPatientAddress

// NewCreateOrderRequestAnyOfPatientAddress instantiates a new CreateOrderRequestAnyOfPatientAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestAnyOfPatientAddress(city string, line1 string, postalCode string, state string) *CreateOrderRequestAnyOfPatientAddress {
	this := CreateOrderRequestAnyOfPatientAddress{}
	this.City = city
	var country string = "US"
	this.Country = &country
	this.Line1 = line1
	this.PostalCode = postalCode
	this.State = state
	return &this
}

// NewCreateOrderRequestAnyOfPatientAddressWithDefaults instantiates a new CreateOrderRequestAnyOfPatientAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestAnyOfPatientAddressWithDefaults() *CreateOrderRequestAnyOfPatientAddress {
	this := CreateOrderRequestAnyOfPatientAddress{}
	var country string = "US"
	this.Country = &country
	return &this
}

// GetCity returns the City field value
func (o *CreateOrderRequestAnyOfPatientAddress) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOfPatientAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *CreateOrderRequestAnyOfPatientAddress) SetCity(v string) {
	o.City = v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *CreateOrderRequestAnyOfPatientAddress) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOfPatientAddress) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *CreateOrderRequestAnyOfPatientAddress) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *CreateOrderRequestAnyOfPatientAddress) SetCountry(v string) {
	o.Country = &v
}

// GetLine1 returns the Line1 field value
func (o *CreateOrderRequestAnyOfPatientAddress) GetLine1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Line1
}

// GetLine1Ok returns a tuple with the Line1 field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOfPatientAddress) GetLine1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Line1, true
}

// SetLine1 sets field value
func (o *CreateOrderRequestAnyOfPatientAddress) SetLine1(v string) {
	o.Line1 = v
}

// GetLine2 returns the Line2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestAnyOfPatientAddress) GetLine2() string {
	if o == nil || IsNil(o.Line2.Get()) {
		var ret string
		return ret
	}
	return *o.Line2.Get()
}

// GetLine2Ok returns a tuple with the Line2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestAnyOfPatientAddress) GetLine2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Line2.Get(), o.Line2.IsSet()
}

// HasLine2 returns a boolean if a field has been set.
func (o *CreateOrderRequestAnyOfPatientAddress) HasLine2() bool {
	if o != nil && o.Line2.IsSet() {
		return true
	}

	return false
}

// SetLine2 gets a reference to the given NullableString and assigns it to the Line2 field.
func (o *CreateOrderRequestAnyOfPatientAddress) SetLine2(v string) {
	o.Line2.Set(&v)
}

// SetLine2Nil sets the value for Line2 to be an explicit nil
func (o *CreateOrderRequestAnyOfPatientAddress) SetLine2Nil() {
	o.Line2.Set(nil)
}

// UnsetLine2 ensures that no value is present for Line2, not even an explicit nil
func (o *CreateOrderRequestAnyOfPatientAddress) UnsetLine2() {
	o.Line2.Unset()
}

// GetPostalCode returns the PostalCode field value
func (o *CreateOrderRequestAnyOfPatientAddress) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOfPatientAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *CreateOrderRequestAnyOfPatientAddress) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetState returns the State field value
func (o *CreateOrderRequestAnyOfPatientAddress) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestAnyOfPatientAddress) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CreateOrderRequestAnyOfPatientAddress) SetState(v string) {
	o.State = v
}

func (o CreateOrderRequestAnyOfPatientAddress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderRequestAnyOfPatientAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["city"] = o.City
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	toSerialize["line1"] = o.Line1
	if o.Line2.IsSet() {
		toSerialize["line2"] = o.Line2.Get()
	}
	toSerialize["postalCode"] = o.PostalCode
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *CreateOrderRequestAnyOfPatientAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"city",
		"line1",
		"postalCode",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrderRequestAnyOfPatientAddress := _CreateOrderRequestAnyOfPatientAddress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrderRequestAnyOfPatientAddress)

	if err != nil {
		return err
	}

	*o = CreateOrderRequestAnyOfPatientAddress(varCreateOrderRequestAnyOfPatientAddress)

	return err
}

type NullableCreateOrderRequestAnyOfPatientAddress struct {
	value *CreateOrderRequestAnyOfPatientAddress
	isSet bool
}

func (v NullableCreateOrderRequestAnyOfPatientAddress) Get() *CreateOrderRequestAnyOfPatientAddress {
	return v.value
}

func (v *NullableCreateOrderRequestAnyOfPatientAddress) Set(val *CreateOrderRequestAnyOfPatientAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestAnyOfPatientAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestAnyOfPatientAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestAnyOfPatientAddress(val *CreateOrderRequestAnyOfPatientAddress) *NullableCreateOrderRequestAnyOfPatientAddress {
	return &NullableCreateOrderRequestAnyOfPatientAddress{value: val, isSet: true}
}

func (v NullableCreateOrderRequestAnyOfPatientAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestAnyOfPatientAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
