/*
Affinity API

Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

API version: 2026-07-19
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateWebhookEndpointResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateWebhookEndpointResponse{}

// UpdateWebhookEndpointResponse struct for UpdateWebhookEndpointResponse
type UpdateWebhookEndpointResponse struct {
	CreatedAt     string   `json:"createdAt"`
	EnabledEvents []string `json:"enabledEvents"`
	Id            string   `json:"id" validate:"regexp=^whe_[0-9a-hjkmnp-tv-z]{26}$"`
	Livemode      bool     `json:"livemode"`
	Object        string   `json:"object"`
	Status        string   `json:"status"`
	UpdatedAt     string   `json:"updatedAt"`
	Url           string   `json:"url"`
}

type _UpdateWebhookEndpointResponse UpdateWebhookEndpointResponse

// NewUpdateWebhookEndpointResponse instantiates a new UpdateWebhookEndpointResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateWebhookEndpointResponse(createdAt string, enabledEvents []string, id string, livemode bool, object string, status string, updatedAt string, url string) *UpdateWebhookEndpointResponse {
	this := UpdateWebhookEndpointResponse{}
	this.CreatedAt = createdAt
	this.EnabledEvents = enabledEvents
	this.Id = id
	this.Livemode = livemode
	this.Object = object
	this.Status = status
	this.UpdatedAt = updatedAt
	this.Url = url
	return &this
}

// NewUpdateWebhookEndpointResponseWithDefaults instantiates a new UpdateWebhookEndpointResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateWebhookEndpointResponseWithDefaults() *UpdateWebhookEndpointResponse {
	this := UpdateWebhookEndpointResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *UpdateWebhookEndpointResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UpdateWebhookEndpointResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetEnabledEvents returns the EnabledEvents field value
func (o *UpdateWebhookEndpointResponse) GetEnabledEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.EnabledEvents
}

// GetEnabledEventsOk returns a tuple with the EnabledEvents field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointResponse) GetEnabledEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnabledEvents, true
}

// SetEnabledEvents sets field value
func (o *UpdateWebhookEndpointResponse) SetEnabledEvents(v []string) {
	o.EnabledEvents = v
}

// GetId returns the Id field value
func (o *UpdateWebhookEndpointResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateWebhookEndpointResponse) SetId(v string) {
	o.Id = v
}

// GetLivemode returns the Livemode field value
func (o *UpdateWebhookEndpointResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *UpdateWebhookEndpointResponse) SetLivemode(v bool) {
	o.Livemode = v
}

// GetObject returns the Object field value
func (o *UpdateWebhookEndpointResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *UpdateWebhookEndpointResponse) SetObject(v string) {
	o.Object = v
}

// GetStatus returns the Status field value
func (o *UpdateWebhookEndpointResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateWebhookEndpointResponse) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UpdateWebhookEndpointResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UpdateWebhookEndpointResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
func (o *UpdateWebhookEndpointResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *UpdateWebhookEndpointResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *UpdateWebhookEndpointResponse) SetUrl(v string) {
	o.Url = v
}

func (o UpdateWebhookEndpointResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateWebhookEndpointResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["enabledEvents"] = o.EnabledEvents
	toSerialize["id"] = o.Id
	toSerialize["livemode"] = o.Livemode
	toSerialize["object"] = o.Object
	toSerialize["status"] = o.Status
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *UpdateWebhookEndpointResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"enabledEvents",
		"id",
		"livemode",
		"object",
		"status",
		"updatedAt",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateWebhookEndpointResponse := _UpdateWebhookEndpointResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateWebhookEndpointResponse)

	if err != nil {
		return err
	}

	*o = UpdateWebhookEndpointResponse(varUpdateWebhookEndpointResponse)

	return err
}

type NullableUpdateWebhookEndpointResponse struct {
	value *UpdateWebhookEndpointResponse
	isSet bool
}

func (v NullableUpdateWebhookEndpointResponse) Get() *UpdateWebhookEndpointResponse {
	return v.value
}

func (v *NullableUpdateWebhookEndpointResponse) Set(val *UpdateWebhookEndpointResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateWebhookEndpointResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateWebhookEndpointResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateWebhookEndpointResponse(val *UpdateWebhookEndpointResponse) *NullableUpdateWebhookEndpointResponse {
	return &NullableUpdateWebhookEndpointResponse{value: val, isSet: true}
}

func (v NullableUpdateWebhookEndpointResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateWebhookEndpointResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
