/*
Affinity API

Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

API version: 2026-07-19
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ListPracticesResponseDataInnerContactsCompliance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPracticesResponseDataInnerContactsCompliance{}

// ListPracticesResponseDataInnerContactsCompliance struct for ListPracticesResponseDataInnerContactsCompliance
type ListPracticesResponseDataInnerContactsCompliance struct {
	Email string         `json:"email" validate:"regexp=^(?!\\\\.)(?!.*\\\\.\\\\.)([A-Za-z0-9_'+\\\\-\\\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\\\-]*\\\\.)+[A-Za-z]{2,}$"`
	Name  string         `json:"name"`
	Phone NullableString `json:"phone"`
}

type _ListPracticesResponseDataInnerContactsCompliance ListPracticesResponseDataInnerContactsCompliance

// NewListPracticesResponseDataInnerContactsCompliance instantiates a new ListPracticesResponseDataInnerContactsCompliance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPracticesResponseDataInnerContactsCompliance(email string, name string, phone NullableString) *ListPracticesResponseDataInnerContactsCompliance {
	this := ListPracticesResponseDataInnerContactsCompliance{}
	this.Email = email
	this.Name = name
	this.Phone = phone
	return &this
}

// NewListPracticesResponseDataInnerContactsComplianceWithDefaults instantiates a new ListPracticesResponseDataInnerContactsCompliance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPracticesResponseDataInnerContactsComplianceWithDefaults() *ListPracticesResponseDataInnerContactsCompliance {
	this := ListPracticesResponseDataInnerContactsCompliance{}
	return &this
}

// GetEmail returns the Email field value
func (o *ListPracticesResponseDataInnerContactsCompliance) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ListPracticesResponseDataInnerContactsCompliance) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ListPracticesResponseDataInnerContactsCompliance) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value
func (o *ListPracticesResponseDataInnerContactsCompliance) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListPracticesResponseDataInnerContactsCompliance) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListPracticesResponseDataInnerContactsCompliance) SetName(v string) {
	o.Name = v
}

// GetPhone returns the Phone field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListPracticesResponseDataInnerContactsCompliance) GetPhone() string {
	if o == nil || o.Phone.Get() == nil {
		var ret string
		return ret
	}

	return *o.Phone.Get()
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListPracticesResponseDataInnerContactsCompliance) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phone.Get(), o.Phone.IsSet()
}

// SetPhone sets field value
func (o *ListPracticesResponseDataInnerContactsCompliance) SetPhone(v string) {
	o.Phone.Set(&v)
}

func (o ListPracticesResponseDataInnerContactsCompliance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPracticesResponseDataInnerContactsCompliance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["name"] = o.Name
	toSerialize["phone"] = o.Phone.Get()
	return toSerialize, nil
}

func (o *ListPracticesResponseDataInnerContactsCompliance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"name",
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPracticesResponseDataInnerContactsCompliance := _ListPracticesResponseDataInnerContactsCompliance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListPracticesResponseDataInnerContactsCompliance)

	if err != nil {
		return err
	}

	*o = ListPracticesResponseDataInnerContactsCompliance(varListPracticesResponseDataInnerContactsCompliance)

	return err
}

type NullableListPracticesResponseDataInnerContactsCompliance struct {
	value *ListPracticesResponseDataInnerContactsCompliance
	isSet bool
}

func (v NullableListPracticesResponseDataInnerContactsCompliance) Get() *ListPracticesResponseDataInnerContactsCompliance {
	return v.value
}

func (v *NullableListPracticesResponseDataInnerContactsCompliance) Set(val *ListPracticesResponseDataInnerContactsCompliance) {
	v.value = val
	v.isSet = true
}

func (v NullableListPracticesResponseDataInnerContactsCompliance) IsSet() bool {
	return v.isSet
}

func (v *NullableListPracticesResponseDataInnerContactsCompliance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPracticesResponseDataInnerContactsCompliance(val *ListPracticesResponseDataInnerContactsCompliance) *NullableListPracticesResponseDataInnerContactsCompliance {
	return &NullableListPracticesResponseDataInnerContactsCompliance{value: val, isSet: true}
}

func (v NullableListPracticesResponseDataInnerContactsCompliance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPracticesResponseDataInnerContactsCompliance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
