/*
Affinity API

Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.

API version: 2026-07-09
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"encoding/json"
	"fmt"
)

// checks if the ListOrderEvents200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOrderEvents200Response{}

// ListOrderEvents200Response struct for ListOrderEvents200Response
type ListOrderEvents200Response struct {
	Events               []ListOrderEvents200ResponseEventsInner `json:"events"`
	AdditionalProperties map[string]interface{}
}

type _ListOrderEvents200Response ListOrderEvents200Response

// NewListOrderEvents200Response instantiates a new ListOrderEvents200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOrderEvents200Response(events []ListOrderEvents200ResponseEventsInner) *ListOrderEvents200Response {
	this := ListOrderEvents200Response{}
	this.Events = events
	return &this
}

// NewListOrderEvents200ResponseWithDefaults instantiates a new ListOrderEvents200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOrderEvents200ResponseWithDefaults() *ListOrderEvents200Response {
	this := ListOrderEvents200Response{}
	return &this
}

// GetEvents returns the Events field value
func (o *ListOrderEvents200Response) GetEvents() []ListOrderEvents200ResponseEventsInner {
	if o == nil {
		var ret []ListOrderEvents200ResponseEventsInner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *ListOrderEvents200Response) GetEventsOk() ([]ListOrderEvents200ResponseEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *ListOrderEvents200Response) SetEvents(v []ListOrderEvents200ResponseEventsInner) {
	o.Events = v
}

func (o ListOrderEvents200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOrderEvents200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOrderEvents200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListOrderEvents200Response := _ListOrderEvents200Response{}

	err = json.Unmarshal(data, &varListOrderEvents200Response)

	if err != nil {
		return err
	}

	*o = ListOrderEvents200Response(varListOrderEvents200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOrderEvents200Response struct {
	value *ListOrderEvents200Response
	isSet bool
}

func (v NullableListOrderEvents200Response) Get() *ListOrderEvents200Response {
	return v.value
}

func (v *NullableListOrderEvents200Response) Set(val *ListOrderEvents200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListOrderEvents200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListOrderEvents200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOrderEvents200Response(val *ListOrderEvents200Response) *NullableListOrderEvents200Response {
	return &NullableListOrderEvents200Response{value: val, isSet: true}
}

func (v NullableListOrderEvents200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOrderEvents200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
