/*
Affinity API

Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.

API version: 2026-07-19
Contact: support@joinaffinityai.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affinity

import (
	"encoding/json"
	"fmt"
)

// checks if the ListPracticesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPracticesResponse{}

// ListPracticesResponse struct for ListPracticesResponse
type ListPracticesResponse struct {
	Data                 []ListPracticesResponseDataInner `json:"data"`
	HasMore              bool                             `json:"hasMore"`
	Object               string                           `json:"object"`
	Url                  string                           `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _ListPracticesResponse ListPracticesResponse

// NewListPracticesResponse instantiates a new ListPracticesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPracticesResponse(data []ListPracticesResponseDataInner, hasMore bool, object string, url string) *ListPracticesResponse {
	this := ListPracticesResponse{}
	this.Data = data
	this.HasMore = hasMore
	this.Object = object
	this.Url = url
	return &this
}

// NewListPracticesResponseWithDefaults instantiates a new ListPracticesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPracticesResponseWithDefaults() *ListPracticesResponse {
	this := ListPracticesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListPracticesResponse) GetData() []ListPracticesResponseDataInner {
	if o == nil {
		var ret []ListPracticesResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListPracticesResponse) GetDataOk() ([]ListPracticesResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListPracticesResponse) SetData(v []ListPracticesResponseDataInner) {
	o.Data = v
}

// GetHasMore returns the HasMore field value
func (o *ListPracticesResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListPracticesResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListPracticesResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetObject returns the Object field value
func (o *ListPracticesResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ListPracticesResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ListPracticesResponse) SetObject(v string) {
	o.Object = v
}

// GetUrl returns the Url field value
func (o *ListPracticesResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ListPracticesResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ListPracticesResponse) SetUrl(v string) {
	o.Url = v
}

func (o ListPracticesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPracticesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["hasMore"] = o.HasMore
	toSerialize["object"] = o.Object
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListPracticesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"hasMore",
		"object",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPracticesResponse := _ListPracticesResponse{}

	err = json.Unmarshal(data, &varListPracticesResponse)

	if err != nil {
		return err
	}

	*o = ListPracticesResponse(varListPracticesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "hasMore")
		delete(additionalProperties, "object")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListPracticesResponse struct {
	value *ListPracticesResponse
	isSet bool
}

func (v NullableListPracticesResponse) Get() *ListPracticesResponse {
	return v.value
}

func (v *NullableListPracticesResponse) Set(val *ListPracticesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListPracticesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListPracticesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPracticesResponse(val *ListPracticesResponse) *NullableListPracticesResponse {
	return &NullableListPracticesResponse{value: val, isSet: true}
}

func (v NullableListPracticesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPracticesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
