/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * CreatePracticeRequestAttestations
 */
@JsonPropertyOrder({
  CreatePracticeRequestAttestations.JSON_PROPERTY_AUTHORIZED_PHI_TRANSFER,
  CreatePracticeRequestAttestations.JSON_PROPERTY_AUTHORIZED_PRACTICE_RELATIONSHIP,
  CreatePracticeRequestAttestations.JSON_PROPERTY_MINIMUM_NECESSARY_PHI,
  CreatePracticeRequestAttestations.JSON_PROPERTY_PROVIDER_DATA_ACCURACY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T21:14:02.112335-04:00[America/Detroit]", comments = "Generator version: 7.22.0")
public class CreatePracticeRequestAttestations {
  public static final String JSON_PROPERTY_AUTHORIZED_PHI_TRANSFER = "authorizedPhiTransfer";
  @javax.annotation.Nonnull
  private Boolean authorizedPhiTransfer;

  public static final String JSON_PROPERTY_AUTHORIZED_PRACTICE_RELATIONSHIP = "authorizedPracticeRelationship";
  @javax.annotation.Nonnull
  private Boolean authorizedPracticeRelationship;

  public static final String JSON_PROPERTY_MINIMUM_NECESSARY_PHI = "minimumNecessaryPhi";
  @javax.annotation.Nonnull
  private Boolean minimumNecessaryPhi;

  public static final String JSON_PROPERTY_PROVIDER_DATA_ACCURACY = "providerDataAccuracy";
  @javax.annotation.Nonnull
  private Boolean providerDataAccuracy;

  public CreatePracticeRequestAttestations() { 
  }

  public CreatePracticeRequestAttestations authorizedPhiTransfer(@javax.annotation.Nonnull Boolean authorizedPhiTransfer) {
    this.authorizedPhiTransfer = authorizedPhiTransfer;
    return this;
  }

  /**
   * Get authorizedPhiTransfer
   * @return authorizedPhiTransfer
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORIZED_PHI_TRANSFER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAuthorizedPhiTransfer() {
    return authorizedPhiTransfer;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORIZED_PHI_TRANSFER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthorizedPhiTransfer(@javax.annotation.Nonnull Boolean authorizedPhiTransfer) {
    this.authorizedPhiTransfer = authorizedPhiTransfer;
  }


  public CreatePracticeRequestAttestations authorizedPracticeRelationship(@javax.annotation.Nonnull Boolean authorizedPracticeRelationship) {
    this.authorizedPracticeRelationship = authorizedPracticeRelationship;
    return this;
  }

  /**
   * Get authorizedPracticeRelationship
   * @return authorizedPracticeRelationship
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORIZED_PRACTICE_RELATIONSHIP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAuthorizedPracticeRelationship() {
    return authorizedPracticeRelationship;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORIZED_PRACTICE_RELATIONSHIP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthorizedPracticeRelationship(@javax.annotation.Nonnull Boolean authorizedPracticeRelationship) {
    this.authorizedPracticeRelationship = authorizedPracticeRelationship;
  }


  public CreatePracticeRequestAttestations minimumNecessaryPhi(@javax.annotation.Nonnull Boolean minimumNecessaryPhi) {
    this.minimumNecessaryPhi = minimumNecessaryPhi;
    return this;
  }

  /**
   * Get minimumNecessaryPhi
   * @return minimumNecessaryPhi
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MINIMUM_NECESSARY_PHI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getMinimumNecessaryPhi() {
    return minimumNecessaryPhi;
  }


  @JsonProperty(value = JSON_PROPERTY_MINIMUM_NECESSARY_PHI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinimumNecessaryPhi(@javax.annotation.Nonnull Boolean minimumNecessaryPhi) {
    this.minimumNecessaryPhi = minimumNecessaryPhi;
  }


  public CreatePracticeRequestAttestations providerDataAccuracy(@javax.annotation.Nonnull Boolean providerDataAccuracy) {
    this.providerDataAccuracy = providerDataAccuracy;
    return this;
  }

  /**
   * Get providerDataAccuracy
   * @return providerDataAccuracy
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_DATA_ACCURACY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getProviderDataAccuracy() {
    return providerDataAccuracy;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_DATA_ACCURACY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProviderDataAccuracy(@javax.annotation.Nonnull Boolean providerDataAccuracy) {
    this.providerDataAccuracy = providerDataAccuracy;
  }


  /**
   * Return true if this createPractice_request_attestations object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePracticeRequestAttestations createPracticeRequestAttestations = (CreatePracticeRequestAttestations) o;
    return Objects.equals(this.authorizedPhiTransfer, createPracticeRequestAttestations.authorizedPhiTransfer) &&
        Objects.equals(this.authorizedPracticeRelationship, createPracticeRequestAttestations.authorizedPracticeRelationship) &&
        Objects.equals(this.minimumNecessaryPhi, createPracticeRequestAttestations.minimumNecessaryPhi) &&
        Objects.equals(this.providerDataAccuracy, createPracticeRequestAttestations.providerDataAccuracy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizedPhiTransfer, authorizedPracticeRelationship, minimumNecessaryPhi, providerDataAccuracy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePracticeRequestAttestations {\n");
    sb.append("    authorizedPhiTransfer: ").append(toIndentedString(authorizedPhiTransfer)).append("\n");
    sb.append("    authorizedPracticeRelationship: ").append(toIndentedString(authorizedPracticeRelationship)).append("\n");
    sb.append("    minimumNecessaryPhi: ").append(toIndentedString(minimumNecessaryPhi)).append("\n");
    sb.append("    providerDataAccuracy: ").append(toIndentedString(providerDataAccuracy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `authorizedPhiTransfer` to the URL query string
    if (getAuthorizedPhiTransfer() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauthorizedPhiTransfer%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthorizedPhiTransfer()))));
    }

    // add `authorizedPracticeRelationship` to the URL query string
    if (getAuthorizedPracticeRelationship() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauthorizedPracticeRelationship%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthorizedPracticeRelationship()))));
    }

    // add `minimumNecessaryPhi` to the URL query string
    if (getMinimumNecessaryPhi() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sminimumNecessaryPhi%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMinimumNecessaryPhi()))));
    }

    // add `providerDataAccuracy` to the URL query string
    if (getProviderDataAccuracy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproviderDataAccuracy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderDataAccuracy()))));
    }

    return joiner.toString();
  }
}

