/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * CreateOrderRequestAnyOfPrescription
 */
@JsonPropertyOrder({
  CreateOrderRequestAnyOfPrescription.JSON_PROPERTY_AUTHORIZED,
  CreateOrderRequestAnyOfPrescription.JSON_PROPERTY_SIGNED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T21:14:02.112335-04:00[America/Detroit]", comments = "Generator version: 7.22.0")
public class CreateOrderRequestAnyOfPrescription {
  /**
   * Gets or Sets authorized
   */
  public enum AuthorizedEnum {
    TRUE(Boolean.valueOf("true"));

    private Boolean value;

    AuthorizedEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AuthorizedEnum fromValue(Boolean value) {
      for (AuthorizedEnum b : AuthorizedEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_AUTHORIZED = "authorized";
  @javax.annotation.Nonnull
  private AuthorizedEnum authorized;

  public static final String JSON_PROPERTY_SIGNED_AT = "signedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime signedAt;

  public CreateOrderRequestAnyOfPrescription() { 
  }

  public CreateOrderRequestAnyOfPrescription authorized(@javax.annotation.Nonnull AuthorizedEnum authorized) {
    this.authorized = authorized;
    return this;
  }

  /**
   * Get authorized
   * @return authorized
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORIZED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AuthorizedEnum getAuthorized() {
    return authorized;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORIZED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthorized(@javax.annotation.Nonnull AuthorizedEnum authorized) {
    this.authorized = authorized;
  }


  public CreateOrderRequestAnyOfPrescription signedAt(@javax.annotation.Nonnull OffsetDateTime signedAt) {
    this.signedAt = signedAt;
    return this;
  }

  /**
   * Get signedAt
   * @return signedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getSignedAt() {
    return signedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignedAt(@javax.annotation.Nonnull OffsetDateTime signedAt) {
    this.signedAt = signedAt;
  }


  /**
   * Return true if this createOrder_request_anyOf_prescription object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderRequestAnyOfPrescription createOrderRequestAnyOfPrescription = (CreateOrderRequestAnyOfPrescription) o;
    return Objects.equals(this.authorized, createOrderRequestAnyOfPrescription.authorized) &&
        Objects.equals(this.signedAt, createOrderRequestAnyOfPrescription.signedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorized, signedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderRequestAnyOfPrescription {\n");
    sb.append("    authorized: ").append(toIndentedString(authorized)).append("\n");
    sb.append("    signedAt: ").append(toIndentedString(signedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `authorized` to the URL query string
    if (getAuthorized() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauthorized%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthorized()))));
    }

    // add `signedAt` to the URL query string
    if (getSignedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssignedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSignedAt()))));
    }

    return joiner.toString();
  }
}

