/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.joinaffinity.sdk.model.CreateWebhookEndpoint200ResponseEndpoint;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * DeleteWebhookEndpoint200Response
 */
@JsonPropertyOrder({
  DeleteWebhookEndpoint200Response.JSON_PROPERTY_ENDPOINT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T21:14:02.112335-04:00[America/Detroit]", comments = "Generator version: 7.22.0")
public class DeleteWebhookEndpoint200Response {
  public static final String JSON_PROPERTY_ENDPOINT = "endpoint";
  @javax.annotation.Nonnull
  private CreateWebhookEndpoint200ResponseEndpoint endpoint;

  public DeleteWebhookEndpoint200Response() { 
  }

  public DeleteWebhookEndpoint200Response endpoint(@javax.annotation.Nonnull CreateWebhookEndpoint200ResponseEndpoint endpoint) {
    this.endpoint = endpoint;
    return this;
  }

  /**
   * Get endpoint
   * @return endpoint
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CreateWebhookEndpoint200ResponseEndpoint getEndpoint() {
    return endpoint;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndpoint(@javax.annotation.Nonnull CreateWebhookEndpoint200ResponseEndpoint endpoint) {
    this.endpoint = endpoint;
  }


  /**
   * Return true if this deleteWebhookEndpoint_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteWebhookEndpoint200Response deleteWebhookEndpoint200Response = (DeleteWebhookEndpoint200Response) o;
    return Objects.equals(this.endpoint, deleteWebhookEndpoint200Response.endpoint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpoint);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteWebhookEndpoint200Response {\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `endpoint` to the URL query string
    if (getEndpoint() != null) {
      joiner.add(getEndpoint().toUrlQueryString(prefix + "endpoint" + suffix));
    }

    return joiner.toString();
  }
}

