/*
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * GetAccountResponseAccount
 */
@JsonPropertyOrder({
  GetAccountResponseAccount.JSON_PROPERTY_ALERT_EMAILS,
  GetAccountResponseAccount.JSON_PROPERTY_ALERT_INTEGRATION_ISSUES,
  GetAccountResponseAccount.JSON_PROPERTY_ALERT_NEW_ORDERS,
  GetAccountResponseAccount.JSON_PROPERTY_ALERT_STATUS_CHANGES,
  GetAccountResponseAccount.JSON_PROPERTY_DISPLAY_NAME,
  GetAccountResponseAccount.JSON_PROPERTY_ID,
  GetAccountResponseAccount.JSON_PROPERTY_OBJECT,
  GetAccountResponseAccount.JSON_PROPERTY_SLUG,
  GetAccountResponseAccount.JSON_PROPERTY_STATUS,
  GetAccountResponseAccount.JSON_PROPERTY_SUPPORT_EMAIL,
  GetAccountResponseAccount.JSON_PROPERTY_WEBSITE_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class GetAccountResponseAccount {
  public static final String JSON_PROPERTY_ALERT_EMAILS = "alertEmails";
  @javax.annotation.Nonnull
  private List<String> alertEmails = new ArrayList<>();

  public static final String JSON_PROPERTY_ALERT_INTEGRATION_ISSUES = "alertIntegrationIssues";
  @javax.annotation.Nonnull
  private Boolean alertIntegrationIssues;

  public static final String JSON_PROPERTY_ALERT_NEW_ORDERS = "alertNewOrders";
  @javax.annotation.Nonnull
  private Boolean alertNewOrders;

  public static final String JSON_PROPERTY_ALERT_STATUS_CHANGES = "alertStatusChanges";
  @javax.annotation.Nonnull
  private Boolean alertStatusChanges;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nonnull
  private String displayName;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  /**
   * Gets or Sets _object
   */
  public enum ObjectEnum {
    ACCOUNT(String.valueOf("account"));

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nonnull
  private ObjectEnum _object;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @javax.annotation.Nonnull
  private String slug;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ACTIVE(String.valueOf("active")),

    PENDING(String.valueOf("pending")),

    SUSPENDED(String.valueOf("suspended"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_SUPPORT_EMAIL = "supportEmail";
  @javax.annotation.Nullable
  private String supportEmail;

  public static final String JSON_PROPERTY_WEBSITE_URL = "websiteUrl";
  @javax.annotation.Nullable
  private String websiteUrl;

  public GetAccountResponseAccount() {
  }

  public GetAccountResponseAccount alertEmails(@javax.annotation.Nonnull List<String> alertEmails) {
    this.alertEmails = alertEmails;
    return this;
  }

  public GetAccountResponseAccount addAlertEmailsItem(String alertEmailsItem) {
    if (this.alertEmails == null) {
      this.alertEmails = new ArrayList<>();
    }
    this.alertEmails.add(alertEmailsItem);
    return this;
  }

  /**
   * Get alertEmails
   * @return alertEmails
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ALERT_EMAILS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getAlertEmails() {
    return alertEmails;
  }


  @JsonProperty(value = JSON_PROPERTY_ALERT_EMAILS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlertEmails(@javax.annotation.Nonnull List<String> alertEmails) {
    this.alertEmails = alertEmails;
  }


  public GetAccountResponseAccount alertIntegrationIssues(@javax.annotation.Nonnull Boolean alertIntegrationIssues) {
    this.alertIntegrationIssues = alertIntegrationIssues;
    return this;
  }

  /**
   * Get alertIntegrationIssues
   * @return alertIntegrationIssues
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ALERT_INTEGRATION_ISSUES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAlertIntegrationIssues() {
    return alertIntegrationIssues;
  }


  @JsonProperty(value = JSON_PROPERTY_ALERT_INTEGRATION_ISSUES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlertIntegrationIssues(@javax.annotation.Nonnull Boolean alertIntegrationIssues) {
    this.alertIntegrationIssues = alertIntegrationIssues;
  }


  public GetAccountResponseAccount alertNewOrders(@javax.annotation.Nonnull Boolean alertNewOrders) {
    this.alertNewOrders = alertNewOrders;
    return this;
  }

  /**
   * Get alertNewOrders
   * @return alertNewOrders
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ALERT_NEW_ORDERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAlertNewOrders() {
    return alertNewOrders;
  }


  @JsonProperty(value = JSON_PROPERTY_ALERT_NEW_ORDERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlertNewOrders(@javax.annotation.Nonnull Boolean alertNewOrders) {
    this.alertNewOrders = alertNewOrders;
  }


  public GetAccountResponseAccount alertStatusChanges(@javax.annotation.Nonnull Boolean alertStatusChanges) {
    this.alertStatusChanges = alertStatusChanges;
    return this;
  }

  /**
   * Get alertStatusChanges
   * @return alertStatusChanges
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ALERT_STATUS_CHANGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAlertStatusChanges() {
    return alertStatusChanges;
  }


  @JsonProperty(value = JSON_PROPERTY_ALERT_STATUS_CHANGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlertStatusChanges(@javax.annotation.Nonnull Boolean alertStatusChanges) {
    this.alertStatusChanges = alertStatusChanges;
  }


  public GetAccountResponseAccount displayName(@javax.annotation.Nonnull String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(@javax.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }


  public GetAccountResponseAccount id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public GetAccountResponseAccount _object(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ObjectEnum getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
  }


  public GetAccountResponseAccount slug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSlug() {
    return slug;
  }


  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }


  public GetAccountResponseAccount status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public GetAccountResponseAccount supportEmail(@javax.annotation.Nullable String supportEmail) {
    this.supportEmail = supportEmail;
    return this;
  }

  /**
   * Get supportEmail
   * @return supportEmail
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUPPORT_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSupportEmail() {
    return supportEmail;
  }


  @JsonProperty(value = JSON_PROPERTY_SUPPORT_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSupportEmail(@javax.annotation.Nullable String supportEmail) {
    this.supportEmail = supportEmail;
  }


  public GetAccountResponseAccount websiteUrl(@javax.annotation.Nullable String websiteUrl) {
    this.websiteUrl = websiteUrl;
    return this;
  }

  /**
   * Get websiteUrl
   * @return websiteUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEBSITE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getWebsiteUrl() {
    return websiteUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBSITE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebsiteUrl(@javax.annotation.Nullable String websiteUrl) {
    this.websiteUrl = websiteUrl;
  }


  /**
   * Return true if this GetAccountResponse_account object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAccountResponseAccount getAccountResponseAccount = (GetAccountResponseAccount) o;
    return Objects.equals(this.alertEmails, getAccountResponseAccount.alertEmails) &&
        Objects.equals(this.alertIntegrationIssues, getAccountResponseAccount.alertIntegrationIssues) &&
        Objects.equals(this.alertNewOrders, getAccountResponseAccount.alertNewOrders) &&
        Objects.equals(this.alertStatusChanges, getAccountResponseAccount.alertStatusChanges) &&
        Objects.equals(this.displayName, getAccountResponseAccount.displayName) &&
        Objects.equals(this.id, getAccountResponseAccount.id) &&
        Objects.equals(this._object, getAccountResponseAccount._object) &&
        Objects.equals(this.slug, getAccountResponseAccount.slug) &&
        Objects.equals(this.status, getAccountResponseAccount.status) &&
        Objects.equals(this.supportEmail, getAccountResponseAccount.supportEmail) &&
        Objects.equals(this.websiteUrl, getAccountResponseAccount.websiteUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alertEmails, alertIntegrationIssues, alertNewOrders, alertStatusChanges, displayName, id, _object, slug, status, supportEmail, websiteUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAccountResponseAccount {\n");
    sb.append("    alertEmails: ").append(toIndentedString(alertEmails)).append("\n");
    sb.append("    alertIntegrationIssues: ").append(toIndentedString(alertIntegrationIssues)).append("\n");
    sb.append("    alertNewOrders: ").append(toIndentedString(alertNewOrders)).append("\n");
    sb.append("    alertStatusChanges: ").append(toIndentedString(alertStatusChanges)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    supportEmail: ").append(toIndentedString(supportEmail)).append("\n");
    sb.append("    websiteUrl: ").append(toIndentedString(websiteUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `alertEmails` to the URL query string
    if (getAlertEmails() != null) {
      for (int i = 0; i < getAlertEmails().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%salertEmails%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAlertEmails().get(i)))));
      }
    }

    // add `alertIntegrationIssues` to the URL query string
    if (getAlertIntegrationIssues() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%salertIntegrationIssues%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAlertIntegrationIssues()))));
    }

    // add `alertNewOrders` to the URL query string
    if (getAlertNewOrders() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%salertNewOrders%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAlertNewOrders()))));
    }

    // add `alertStatusChanges` to the URL query string
    if (getAlertStatusChanges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%salertStatusChanges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAlertStatusChanges()))));
    }

    // add `displayName` to the URL query string
    if (getDisplayName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdisplayName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisplayName()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `object` to the URL query string
    if (getObject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sobject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObject()))));
    }

    // add `slug` to the URL query string
    if (getSlug() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sslug%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSlug()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `supportEmail` to the URL query string
    if (getSupportEmail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssupportEmail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSupportEmail()))));
    }

    // add `websiteUrl` to the URL query string
    if (getWebsiteUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebsiteUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebsiteUrl()))));
    }

    return joiner.toString();
  }
}

