/*
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * GetWebhookEventResponseDeliveriesInner
 */
@JsonPropertyOrder({
  GetWebhookEventResponseDeliveriesInner.JSON_PROPERTY_ATTEMPT_COUNT,
  GetWebhookEventResponseDeliveriesInner.JSON_PROPERTY_ENDPOINT_ID,
  GetWebhookEventResponseDeliveriesInner.JSON_PROPERTY_ID,
  GetWebhookEventResponseDeliveriesInner.JSON_PROPERTY_LAST_ERROR,
  GetWebhookEventResponseDeliveriesInner.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class GetWebhookEventResponseDeliveriesInner {
  public static final String JSON_PROPERTY_ATTEMPT_COUNT = "attemptCount";
  @javax.annotation.Nonnull
  private BigDecimal attemptCount;

  public static final String JSON_PROPERTY_ENDPOINT_ID = "endpointId";
  @javax.annotation.Nonnull
  private String endpointId;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_LAST_ERROR = "lastError";
  @javax.annotation.Nullable
  private String lastError;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    DEAD_LETTER(String.valueOf("dead_letter")),

    DELIVERED(String.valueOf("delivered")),

    FAILED(String.valueOf("failed")),

    PENDING(String.valueOf("pending"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public GetWebhookEventResponseDeliveriesInner() {
  }

  public GetWebhookEventResponseDeliveriesInner attemptCount(@javax.annotation.Nonnull BigDecimal attemptCount) {
    this.attemptCount = attemptCount;
    return this;
  }

  /**
   * Get attemptCount
   * @return attemptCount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ATTEMPT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getAttemptCount() {
    return attemptCount;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTEMPT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttemptCount(@javax.annotation.Nonnull BigDecimal attemptCount) {
    this.attemptCount = attemptCount;
  }


  public GetWebhookEventResponseDeliveriesInner endpointId(@javax.annotation.Nonnull String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

  /**
   * Get endpointId
   * @return endpointId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEndpointId() {
    return endpointId;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndpointId(@javax.annotation.Nonnull String endpointId) {
    this.endpointId = endpointId;
  }


  public GetWebhookEventResponseDeliveriesInner id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public GetWebhookEventResponseDeliveriesInner lastError(@javax.annotation.Nullable String lastError) {
    this.lastError = lastError;
    return this;
  }

  /**
   * Get lastError
   * @return lastError
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLastError() {
    return lastError;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastError(@javax.annotation.Nullable String lastError) {
    this.lastError = lastError;
  }


  public GetWebhookEventResponseDeliveriesInner status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  /**
   * Return true if this GetWebhookEventResponse_deliveries_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetWebhookEventResponseDeliveriesInner getWebhookEventResponseDeliveriesInner = (GetWebhookEventResponseDeliveriesInner) o;
    return Objects.equals(this.attemptCount, getWebhookEventResponseDeliveriesInner.attemptCount) &&
        Objects.equals(this.endpointId, getWebhookEventResponseDeliveriesInner.endpointId) &&
        Objects.equals(this.id, getWebhookEventResponseDeliveriesInner.id) &&
        Objects.equals(this.lastError, getWebhookEventResponseDeliveriesInner.lastError) &&
        Objects.equals(this.status, getWebhookEventResponseDeliveriesInner.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attemptCount, endpointId, id, lastError, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetWebhookEventResponseDeliveriesInner {\n");
    sb.append("    attemptCount: ").append(toIndentedString(attemptCount)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastError: ").append(toIndentedString(lastError)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `attemptCount` to the URL query string
    if (getAttemptCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sattemptCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAttemptCount()))));
    }

    // add `endpointId` to the URL query string
    if (getEndpointId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendpointId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointId()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `lastError` to the URL query string
    if (getLastError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastError%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastError()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    return joiner.toString();
  }
}

