/*
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * ListWebhookEndpointsResponseDataInner
 */
@JsonPropertyOrder({
  ListWebhookEndpointsResponseDataInner.JSON_PROPERTY_CREATED_AT,
  ListWebhookEndpointsResponseDataInner.JSON_PROPERTY_ENABLED_EVENTS,
  ListWebhookEndpointsResponseDataInner.JSON_PROPERTY_LIVEMODE,
  ListWebhookEndpointsResponseDataInner.JSON_PROPERTY_OBJECT,
  ListWebhookEndpointsResponseDataInner.JSON_PROPERTY_UPDATED_AT,
  ListWebhookEndpointsResponseDataInner.JSON_PROPERTY_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class ListWebhookEndpointsResponseDataInner {
  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private String createdAt;

  public static final String JSON_PROPERTY_ENABLED_EVENTS = "enabledEvents";
  @javax.annotation.Nonnull
  private List<String> enabledEvents = new ArrayList<>();

  public static final String JSON_PROPERTY_LIVEMODE = "livemode";
  @javax.annotation.Nonnull
  private Boolean livemode;

  /**
   * Gets or Sets _object
   */
  public enum ObjectEnum {
    WEBHOOK_ENDPOINT(String.valueOf("webhook_endpoint"));

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nonnull
  private ObjectEnum _object;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private String updatedAt;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nonnull
  private String url;

  public ListWebhookEndpointsResponseDataInner() {
  }

  public ListWebhookEndpointsResponseDataInner createdAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  public ListWebhookEndpointsResponseDataInner enabledEvents(@javax.annotation.Nonnull List<String> enabledEvents) {
    this.enabledEvents = enabledEvents;
    return this;
  }

  public ListWebhookEndpointsResponseDataInner addEnabledEventsItem(String enabledEventsItem) {
    if (this.enabledEvents == null) {
      this.enabledEvents = new ArrayList<>();
    }
    this.enabledEvents.add(enabledEventsItem);
    return this;
  }

  /**
   * Get enabledEvents
   * @return enabledEvents
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENABLED_EVENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getEnabledEvents() {
    return enabledEvents;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED_EVENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnabledEvents(@javax.annotation.Nonnull List<String> enabledEvents) {
    this.enabledEvents = enabledEvents;
  }


  public ListWebhookEndpointsResponseDataInner livemode(@javax.annotation.Nonnull Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

  /**
   * Get livemode
   * @return livemode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIVEMODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getLivemode() {
    return livemode;
  }


  @JsonProperty(value = JSON_PROPERTY_LIVEMODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLivemode(@javax.annotation.Nonnull Boolean livemode) {
    this.livemode = livemode;
  }


  public ListWebhookEndpointsResponseDataInner _object(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ObjectEnum getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
  }


  public ListWebhookEndpointsResponseDataInner updatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ListWebhookEndpointsResponseDataInner url(@javax.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@javax.annotation.Nonnull String url) {
    this.url = url;
  }


  /**
   * Return true if this ListWebhookEndpointsResponse_data_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListWebhookEndpointsResponseDataInner listWebhookEndpointsResponseDataInner = (ListWebhookEndpointsResponseDataInner) o;
    return Objects.equals(this.createdAt, listWebhookEndpointsResponseDataInner.createdAt) &&
        Objects.equals(this.enabledEvents, listWebhookEndpointsResponseDataInner.enabledEvents) &&
        Objects.equals(this.livemode, listWebhookEndpointsResponseDataInner.livemode) &&
        Objects.equals(this._object, listWebhookEndpointsResponseDataInner._object) &&
        Objects.equals(this.updatedAt, listWebhookEndpointsResponseDataInner.updatedAt) &&
        Objects.equals(this.url, listWebhookEndpointsResponseDataInner.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, enabledEvents, livemode, _object, updatedAt, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListWebhookEndpointsResponseDataInner {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    enabledEvents: ").append(toIndentedString(enabledEvents)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `enabledEvents` to the URL query string
    if (getEnabledEvents() != null) {
      for (int i = 0; i < getEnabledEvents().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%senabledEvents%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getEnabledEvents().get(i)))));
      }
    }

    // add `livemode` to the URL query string
    if (getLivemode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slivemode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLivemode()))));
    }

    // add `object` to the URL query string
    if (getObject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sobject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObject()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    return joiner.toString();
  }
}

