/*
 * Affinity API
 * Affinity API for platform practices, compounder catalog discovery, prescription-order submission, and fulfillment tracking.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * ListOrders200ResponseOrdersInnerRouting
 */
@JsonPropertyOrder({
  ListOrders200ResponseOrdersInnerRouting.JSON_PROPERTY_BLOCKED_REASONS,
  ListOrders200ResponseOrdersInnerRouting.JSON_PROPERTY_CANDIDATE_COMPOUNDER_IDS,
  ListOrders200ResponseOrdersInnerRouting.JSON_PROPERTY_COLD_SHIP,
  ListOrders200ResponseOrdersInnerRouting.JSON_PROPERTY_SELECTED_COMPOUNDER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T21:14:02.112335-04:00[America/Detroit]", comments = "Generator version: 7.22.0")
public class ListOrders200ResponseOrdersInnerRouting {
  public static final String JSON_PROPERTY_BLOCKED_REASONS = "blockedReasons";
  @javax.annotation.Nonnull
  private List<String> blockedReasons = new ArrayList<>();

  public static final String JSON_PROPERTY_CANDIDATE_COMPOUNDER_IDS = "candidateCompounderIds";
  @javax.annotation.Nonnull
  private List<String> candidateCompounderIds = new ArrayList<>();

  public static final String JSON_PROPERTY_COLD_SHIP = "coldShip";
  @javax.annotation.Nonnull
  private Boolean coldShip;

  public static final String JSON_PROPERTY_SELECTED_COMPOUNDER_ID = "selectedCompounderId";
  @javax.annotation.Nullable
  private String selectedCompounderId;

  public ListOrders200ResponseOrdersInnerRouting() { 
  }

  public ListOrders200ResponseOrdersInnerRouting blockedReasons(@javax.annotation.Nonnull List<String> blockedReasons) {
    this.blockedReasons = blockedReasons;
    return this;
  }

  public ListOrders200ResponseOrdersInnerRouting addBlockedReasonsItem(String blockedReasonsItem) {
    if (this.blockedReasons == null) {
      this.blockedReasons = new ArrayList<>();
    }
    this.blockedReasons.add(blockedReasonsItem);
    return this;
  }

  /**
   * Get blockedReasons
   * @return blockedReasons
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BLOCKED_REASONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getBlockedReasons() {
    return blockedReasons;
  }


  @JsonProperty(value = JSON_PROPERTY_BLOCKED_REASONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBlockedReasons(@javax.annotation.Nonnull List<String> blockedReasons) {
    this.blockedReasons = blockedReasons;
  }


  public ListOrders200ResponseOrdersInnerRouting candidateCompounderIds(@javax.annotation.Nonnull List<String> candidateCompounderIds) {
    this.candidateCompounderIds = candidateCompounderIds;
    return this;
  }

  public ListOrders200ResponseOrdersInnerRouting addCandidateCompounderIdsItem(String candidateCompounderIdsItem) {
    if (this.candidateCompounderIds == null) {
      this.candidateCompounderIds = new ArrayList<>();
    }
    this.candidateCompounderIds.add(candidateCompounderIdsItem);
    return this;
  }

  /**
   * Get candidateCompounderIds
   * @return candidateCompounderIds
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CANDIDATE_COMPOUNDER_IDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getCandidateCompounderIds() {
    return candidateCompounderIds;
  }


  @JsonProperty(value = JSON_PROPERTY_CANDIDATE_COMPOUNDER_IDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCandidateCompounderIds(@javax.annotation.Nonnull List<String> candidateCompounderIds) {
    this.candidateCompounderIds = candidateCompounderIds;
  }


  public ListOrders200ResponseOrdersInnerRouting coldShip(@javax.annotation.Nonnull Boolean coldShip) {
    this.coldShip = coldShip;
    return this;
  }

  /**
   * Get coldShip
   * @return coldShip
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COLD_SHIP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getColdShip() {
    return coldShip;
  }


  @JsonProperty(value = JSON_PROPERTY_COLD_SHIP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColdShip(@javax.annotation.Nonnull Boolean coldShip) {
    this.coldShip = coldShip;
  }


  public ListOrders200ResponseOrdersInnerRouting selectedCompounderId(@javax.annotation.Nullable String selectedCompounderId) {
    this.selectedCompounderId = selectedCompounderId;
    return this;
  }

  /**
   * Get selectedCompounderId
   * @return selectedCompounderId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SELECTED_COMPOUNDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSelectedCompounderId() {
    return selectedCompounderId;
  }


  @JsonProperty(value = JSON_PROPERTY_SELECTED_COMPOUNDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSelectedCompounderId(@javax.annotation.Nullable String selectedCompounderId) {
    this.selectedCompounderId = selectedCompounderId;
  }


  /**
   * Return true if this listOrders_200_response_orders_inner_routing object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListOrders200ResponseOrdersInnerRouting listOrders200ResponseOrdersInnerRouting = (ListOrders200ResponseOrdersInnerRouting) o;
    return Objects.equals(this.blockedReasons, listOrders200ResponseOrdersInnerRouting.blockedReasons) &&
        Objects.equals(this.candidateCompounderIds, listOrders200ResponseOrdersInnerRouting.candidateCompounderIds) &&
        Objects.equals(this.coldShip, listOrders200ResponseOrdersInnerRouting.coldShip) &&
        Objects.equals(this.selectedCompounderId, listOrders200ResponseOrdersInnerRouting.selectedCompounderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockedReasons, candidateCompounderIds, coldShip, selectedCompounderId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListOrders200ResponseOrdersInnerRouting {\n");
    sb.append("    blockedReasons: ").append(toIndentedString(blockedReasons)).append("\n");
    sb.append("    candidateCompounderIds: ").append(toIndentedString(candidateCompounderIds)).append("\n");
    sb.append("    coldShip: ").append(toIndentedString(coldShip)).append("\n");
    sb.append("    selectedCompounderId: ").append(toIndentedString(selectedCompounderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `blockedReasons` to the URL query string
    if (getBlockedReasons() != null) {
      for (int i = 0; i < getBlockedReasons().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sblockedReasons%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getBlockedReasons().get(i)))));
      }
    }

    // add `candidateCompounderIds` to the URL query string
    if (getCandidateCompounderIds() != null) {
      for (int i = 0; i < getCandidateCompounderIds().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scandidateCompounderIds%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCandidateCompounderIds().get(i)))));
      }
    }

    // add `coldShip` to the URL query string
    if (getColdShip() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scoldShip%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColdShip()))));
    }

    // add `selectedCompounderId` to the URL query string
    if (getSelectedCompounderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sselectedCompounderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSelectedCompounderId()))));
    }

    return joiner.toString();
  }
}

