/*
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.joinaffinity.sdk.model.ListOrdersResponseDataInnerRouting;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * ListOrdersResponseDataInner
 */
@JsonPropertyOrder({
  ListOrdersResponseDataInner.JSON_PROPERTY_CANCELLATION_REASON,
  ListOrdersResponseDataInner.JSON_PROPERTY_CARRIER,
  ListOrdersResponseDataInner.JSON_PROPERTY_CATALOG_ITEM_ID,
  ListOrdersResponseDataInner.JSON_PROPERTY_PRACTICE_ID,
  ListOrdersResponseDataInner.JSON_PROPERTY_COMPOUNDER_ID,
  ListOrdersResponseDataInner.JSON_PROPERTY_CREATED_AT,
  ListOrdersResponseDataInner.JSON_PROPERTY_CURRENCY,
  ListOrdersResponseDataInner.JSON_PROPERTY_DIRECTIONS,
  ListOrdersResponseDataInner.JSON_PROPERTY_DOSAGE_FORM,
  ListOrdersResponseDataInner.JSON_PROPERTY_EXTERNAL_ORDER_ID,
  ListOrdersResponseDataInner.JSON_PROPERTY_EXTERNAL_SUBMISSION_ATTEMPTED,
  ListOrdersResponseDataInner.JSON_PROPERTY_EXTERNAL_SUBMISSION_BLOCKED_REASON,
  ListOrdersResponseDataInner.JSON_PROPERTY_ID,
  ListOrdersResponseDataInner.JSON_PROPERTY_LIVEMODE,
  ListOrdersResponseDataInner.JSON_PROPERTY_MEDICATION_NAME,
  ListOrdersResponseDataInner.JSON_PROPERTY_PATIENT_EXTERNAL_ID,
  ListOrdersResponseDataInner.JSON_PROPERTY_PATIENT_NAME,
  ListOrdersResponseDataInner.JSON_PROPERTY_PATIENT_STATE,
  ListOrdersResponseDataInner.JSON_PROPERTY_PRESCRIBER_NAME,
  ListOrdersResponseDataInner.JSON_PROPERTY_PRESCRIBER_NPI,
  ListOrdersResponseDataInner.JSON_PROPERTY_QUANTITY,
  ListOrdersResponseDataInner.JSON_PROPERTY_QUOTE_CENTS,
  ListOrdersResponseDataInner.JSON_PROPERTY_OBJECT,
  ListOrdersResponseDataInner.JSON_PROPERTY_REPLACES_ORDER_ID,
  ListOrdersResponseDataInner.JSON_PROPERTY_ROUTING,
  ListOrdersResponseDataInner.JSON_PROPERTY_STATUS,
  ListOrdersResponseDataInner.JSON_PROPERTY_STRENGTH,
  ListOrdersResponseDataInner.JSON_PROPERTY_TRACKING_NUMBER,
  ListOrdersResponseDataInner.JSON_PROPERTY_SHIPPED_AT,
  ListOrdersResponseDataInner.JSON_PROPERTY_DELIVERED_AT,
  ListOrdersResponseDataInner.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class ListOrdersResponseDataInner {
  public static final String JSON_PROPERTY_CANCELLATION_REASON = "cancellationReason";
  @javax.annotation.Nullable
  private String cancellationReason;

  public static final String JSON_PROPERTY_CARRIER = "carrier";
  @javax.annotation.Nullable
  private String carrier;

  public static final String JSON_PROPERTY_CATALOG_ITEM_ID = "catalogItemId";
  @javax.annotation.Nullable
  private String catalogItemId;

  public static final String JSON_PROPERTY_PRACTICE_ID = "practiceId";
  @javax.annotation.Nonnull
  private String practiceId;

  public static final String JSON_PROPERTY_COMPOUNDER_ID = "compounderId";
  @javax.annotation.Nullable
  private String compounderId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private String createdAt;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_DIRECTIONS = "directions";
  @javax.annotation.Nonnull
  private String directions;

  public static final String JSON_PROPERTY_DOSAGE_FORM = "dosageForm";
  @javax.annotation.Nullable
  private String dosageForm;

  public static final String JSON_PROPERTY_EXTERNAL_ORDER_ID = "externalOrderId";
  @javax.annotation.Nonnull
  private String externalOrderId;

  public static final String JSON_PROPERTY_EXTERNAL_SUBMISSION_ATTEMPTED = "externalSubmissionAttempted";
  @javax.annotation.Nonnull
  private Boolean externalSubmissionAttempted;

  public static final String JSON_PROPERTY_EXTERNAL_SUBMISSION_BLOCKED_REASON = "externalSubmissionBlockedReason";
  @javax.annotation.Nullable
  private String externalSubmissionBlockedReason;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_LIVEMODE = "livemode";
  @javax.annotation.Nonnull
  private Boolean livemode;

  public static final String JSON_PROPERTY_MEDICATION_NAME = "medicationName";
  @javax.annotation.Nonnull
  private String medicationName;

  public static final String JSON_PROPERTY_PATIENT_EXTERNAL_ID = "patientExternalId";
  @javax.annotation.Nonnull
  private String patientExternalId;

  public static final String JSON_PROPERTY_PATIENT_NAME = "patientName";
  @javax.annotation.Nonnull
  private String patientName;

  public static final String JSON_PROPERTY_PATIENT_STATE = "patientState";
  @javax.annotation.Nonnull
  private String patientState;

  public static final String JSON_PROPERTY_PRESCRIBER_NAME = "prescriberName";
  @javax.annotation.Nullable
  private String prescriberName;

  public static final String JSON_PROPERTY_PRESCRIBER_NPI = "prescriberNpi";
  @javax.annotation.Nullable
  private String prescriberNpi;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @javax.annotation.Nonnull
  private BigDecimal quantity;

  public static final String JSON_PROPERTY_QUOTE_CENTS = "quoteCents";
  @javax.annotation.Nullable
  private BigDecimal quoteCents;

  /**
   * Gets or Sets _object
   */
  public enum ObjectEnum {
    ORDER(String.valueOf("order"));

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nonnull
  private ObjectEnum _object;

  public static final String JSON_PROPERTY_REPLACES_ORDER_ID = "replacesOrderId";
  @javax.annotation.Nullable
  private String replacesOrderId;

  public static final String JSON_PROPERTY_ROUTING = "routing";
  @javax.annotation.Nullable
  private ListOrdersResponseDataInnerRouting routing;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    BLOCKED(String.valueOf("blocked")),

    CANCELLED(String.valueOf("cancelled")),

    DELIVERED(String.valueOf("delivered")),

    DRAFT(String.valueOf("draft")),

    PROCESSING(String.valueOf("processing")),

    SHIPPED(String.valueOf("shipped")),

    SUBMITTED(String.valueOf("submitted"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_STRENGTH = "strength";
  @javax.annotation.Nullable
  private String strength;

  public static final String JSON_PROPERTY_TRACKING_NUMBER = "trackingNumber";
  @javax.annotation.Nullable
  private String trackingNumber;

  public static final String JSON_PROPERTY_SHIPPED_AT = "shippedAt";
  @javax.annotation.Nullable
  private String shippedAt;

  public static final String JSON_PROPERTY_DELIVERED_AT = "deliveredAt";
  @javax.annotation.Nullable
  private String deliveredAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private String updatedAt;

  public ListOrdersResponseDataInner() {
  }

  public ListOrdersResponseDataInner cancellationReason(@javax.annotation.Nullable String cancellationReason) {
    this.cancellationReason = cancellationReason;
    return this;
  }

  /**
   * Get cancellationReason
   * @return cancellationReason
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CANCELLATION_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCancellationReason() {
    return cancellationReason;
  }


  @JsonProperty(value = JSON_PROPERTY_CANCELLATION_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCancellationReason(@javax.annotation.Nullable String cancellationReason) {
    this.cancellationReason = cancellationReason;
  }


  public ListOrdersResponseDataInner carrier(@javax.annotation.Nullable String carrier) {
    this.carrier = carrier;
    return this;
  }

  /**
   * Get carrier
   * @return carrier
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CARRIER, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCarrier() {
    return carrier;
  }


  @JsonProperty(value = JSON_PROPERTY_CARRIER, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCarrier(@javax.annotation.Nullable String carrier) {
    this.carrier = carrier;
  }


  public ListOrdersResponseDataInner catalogItemId(@javax.annotation.Nullable String catalogItemId) {
    this.catalogItemId = catalogItemId;
    return this;
  }

  /**
   * Get catalogItemId
   * @return catalogItemId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CATALOG_ITEM_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCatalogItemId() {
    return catalogItemId;
  }


  @JsonProperty(value = JSON_PROPERTY_CATALOG_ITEM_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCatalogItemId(@javax.annotation.Nullable String catalogItemId) {
    this.catalogItemId = catalogItemId;
  }


  public ListOrdersResponseDataInner practiceId(@javax.annotation.Nonnull String practiceId) {
    this.practiceId = practiceId;
    return this;
  }

  /**
   * Get practiceId
   * @return practiceId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRACTICE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPracticeId() {
    return practiceId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRACTICE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPracticeId(@javax.annotation.Nonnull String practiceId) {
    this.practiceId = practiceId;
  }


  public ListOrdersResponseDataInner compounderId(@javax.annotation.Nullable String compounderId) {
    this.compounderId = compounderId;
    return this;
  }

  /**
   * Get compounderId
   * @return compounderId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPOUNDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCompounderId() {
    return compounderId;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPOUNDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompounderId(@javax.annotation.Nullable String compounderId) {
    this.compounderId = compounderId;
  }


  public ListOrdersResponseDataInner createdAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  public ListOrdersResponseDataInner currency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public ListOrdersResponseDataInner directions(@javax.annotation.Nonnull String directions) {
    this.directions = directions;
    return this;
  }

  /**
   * Get directions
   * @return directions
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DIRECTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDirections() {
    return directions;
  }


  @JsonProperty(value = JSON_PROPERTY_DIRECTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDirections(@javax.annotation.Nonnull String directions) {
    this.directions = directions;
  }


  public ListOrdersResponseDataInner dosageForm(@javax.annotation.Nullable String dosageForm) {
    this.dosageForm = dosageForm;
    return this;
  }

  /**
   * Get dosageForm
   * @return dosageForm
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOSAGE_FORM, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDosageForm() {
    return dosageForm;
  }


  @JsonProperty(value = JSON_PROPERTY_DOSAGE_FORM, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDosageForm(@javax.annotation.Nullable String dosageForm) {
    this.dosageForm = dosageForm;
  }


  public ListOrdersResponseDataInner externalOrderId(@javax.annotation.Nonnull String externalOrderId) {
    this.externalOrderId = externalOrderId;
    return this;
  }

  /**
   * Get externalOrderId
   * @return externalOrderId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ORDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getExternalOrderId() {
    return externalOrderId;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ORDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalOrderId(@javax.annotation.Nonnull String externalOrderId) {
    this.externalOrderId = externalOrderId;
  }


  public ListOrdersResponseDataInner externalSubmissionAttempted(@javax.annotation.Nonnull Boolean externalSubmissionAttempted) {
    this.externalSubmissionAttempted = externalSubmissionAttempted;
    return this;
  }

  /**
   * Get externalSubmissionAttempted
   * @return externalSubmissionAttempted
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_SUBMISSION_ATTEMPTED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getExternalSubmissionAttempted() {
    return externalSubmissionAttempted;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_SUBMISSION_ATTEMPTED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalSubmissionAttempted(@javax.annotation.Nonnull Boolean externalSubmissionAttempted) {
    this.externalSubmissionAttempted = externalSubmissionAttempted;
  }


  public ListOrdersResponseDataInner externalSubmissionBlockedReason(@javax.annotation.Nullable String externalSubmissionBlockedReason) {
    this.externalSubmissionBlockedReason = externalSubmissionBlockedReason;
    return this;
  }

  /**
   * Get externalSubmissionBlockedReason
   * @return externalSubmissionBlockedReason
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_SUBMISSION_BLOCKED_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getExternalSubmissionBlockedReason() {
    return externalSubmissionBlockedReason;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_SUBMISSION_BLOCKED_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalSubmissionBlockedReason(@javax.annotation.Nullable String externalSubmissionBlockedReason) {
    this.externalSubmissionBlockedReason = externalSubmissionBlockedReason;
  }


  public ListOrdersResponseDataInner id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public ListOrdersResponseDataInner livemode(@javax.annotation.Nonnull Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

  /**
   * Get livemode
   * @return livemode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIVEMODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getLivemode() {
    return livemode;
  }


  @JsonProperty(value = JSON_PROPERTY_LIVEMODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLivemode(@javax.annotation.Nonnull Boolean livemode) {
    this.livemode = livemode;
  }


  public ListOrdersResponseDataInner medicationName(@javax.annotation.Nonnull String medicationName) {
    this.medicationName = medicationName;
    return this;
  }

  /**
   * Get medicationName
   * @return medicationName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MEDICATION_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMedicationName() {
    return medicationName;
  }


  @JsonProperty(value = JSON_PROPERTY_MEDICATION_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMedicationName(@javax.annotation.Nonnull String medicationName) {
    this.medicationName = medicationName;
  }


  public ListOrdersResponseDataInner patientExternalId(@javax.annotation.Nonnull String patientExternalId) {
    this.patientExternalId = patientExternalId;
    return this;
  }

  /**
   * Get patientExternalId
   * @return patientExternalId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATIENT_EXTERNAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPatientExternalId() {
    return patientExternalId;
  }


  @JsonProperty(value = JSON_PROPERTY_PATIENT_EXTERNAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPatientExternalId(@javax.annotation.Nonnull String patientExternalId) {
    this.patientExternalId = patientExternalId;
  }


  public ListOrdersResponseDataInner patientName(@javax.annotation.Nonnull String patientName) {
    this.patientName = patientName;
    return this;
  }

  /**
   * Get patientName
   * @return patientName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATIENT_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPatientName() {
    return patientName;
  }


  @JsonProperty(value = JSON_PROPERTY_PATIENT_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPatientName(@javax.annotation.Nonnull String patientName) {
    this.patientName = patientName;
  }


  public ListOrdersResponseDataInner patientState(@javax.annotation.Nonnull String patientState) {
    this.patientState = patientState;
    return this;
  }

  /**
   * Get patientState
   * @return patientState
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATIENT_STATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPatientState() {
    return patientState;
  }


  @JsonProperty(value = JSON_PROPERTY_PATIENT_STATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPatientState(@javax.annotation.Nonnull String patientState) {
    this.patientState = patientState;
  }


  public ListOrdersResponseDataInner prescriberName(@javax.annotation.Nullable String prescriberName) {
    this.prescriberName = prescriberName;
    return this;
  }

  /**
   * Get prescriberName
   * @return prescriberName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRESCRIBER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPrescriberName() {
    return prescriberName;
  }


  @JsonProperty(value = JSON_PROPERTY_PRESCRIBER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrescriberName(@javax.annotation.Nullable String prescriberName) {
    this.prescriberName = prescriberName;
  }


  public ListOrdersResponseDataInner prescriberNpi(@javax.annotation.Nullable String prescriberNpi) {
    this.prescriberNpi = prescriberNpi;
    return this;
  }

  /**
   * Get prescriberNpi
   * @return prescriberNpi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRESCRIBER_NPI, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPrescriberNpi() {
    return prescriberNpi;
  }


  @JsonProperty(value = JSON_PROPERTY_PRESCRIBER_NPI, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrescriberNpi(@javax.annotation.Nullable String prescriberNpi) {
    this.prescriberNpi = prescriberNpi;
  }


  public ListOrdersResponseDataInner quantity(@javax.annotation.Nonnull BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getQuantity() {
    return quantity;
  }


  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(@javax.annotation.Nonnull BigDecimal quantity) {
    this.quantity = quantity;
  }


  public ListOrdersResponseDataInner quoteCents(@javax.annotation.Nullable BigDecimal quoteCents) {
    this.quoteCents = quoteCents;
    return this;
  }

  /**
   * Get quoteCents
   * @return quoteCents
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUOTE_CENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getQuoteCents() {
    return quoteCents;
  }


  @JsonProperty(value = JSON_PROPERTY_QUOTE_CENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuoteCents(@javax.annotation.Nullable BigDecimal quoteCents) {
    this.quoteCents = quoteCents;
  }


  public ListOrdersResponseDataInner _object(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ObjectEnum getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
  }


  public ListOrdersResponseDataInner replacesOrderId(@javax.annotation.Nullable String replacesOrderId) {
    this.replacesOrderId = replacesOrderId;
    return this;
  }

  /**
   * Get replacesOrderId
   * @return replacesOrderId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLACES_ORDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getReplacesOrderId() {
    return replacesOrderId;
  }


  @JsonProperty(value = JSON_PROPERTY_REPLACES_ORDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReplacesOrderId(@javax.annotation.Nullable String replacesOrderId) {
    this.replacesOrderId = replacesOrderId;
  }


  public ListOrdersResponseDataInner routing(@javax.annotation.Nullable ListOrdersResponseDataInnerRouting routing) {
    this.routing = routing;
    return this;
  }

  /**
   * Get routing
   * @return routing
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROUTING, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ListOrdersResponseDataInnerRouting getRouting() {
    return routing;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTING, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouting(@javax.annotation.Nullable ListOrdersResponseDataInnerRouting routing) {
    this.routing = routing;
  }


  public ListOrdersResponseDataInner status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public ListOrdersResponseDataInner strength(@javax.annotation.Nullable String strength) {
    this.strength = strength;
    return this;
  }

  /**
   * Get strength
   * @return strength
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STRENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStrength() {
    return strength;
  }


  @JsonProperty(value = JSON_PROPERTY_STRENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStrength(@javax.annotation.Nullable String strength) {
    this.strength = strength;
  }


  public ListOrdersResponseDataInner trackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

  /**
   * Get trackingNumber
   * @return trackingNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACKING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTrackingNumber() {
    return trackingNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }


  public ListOrdersResponseDataInner shippedAt(@javax.annotation.Nullable String shippedAt) {
    this.shippedAt = shippedAt;
    return this;
  }

  /**
   * Get shippedAt
   * @return shippedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHIPPED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getShippedAt() {
    return shippedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_SHIPPED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShippedAt(@javax.annotation.Nullable String shippedAt) {
    this.shippedAt = shippedAt;
  }


  public ListOrdersResponseDataInner deliveredAt(@javax.annotation.Nullable String deliveredAt) {
    this.deliveredAt = deliveredAt;
    return this;
  }

  /**
   * Get deliveredAt
   * @return deliveredAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELIVERED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDeliveredAt() {
    return deliveredAt;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeliveredAt(@javax.annotation.Nullable String deliveredAt) {
    this.deliveredAt = deliveredAt;
  }


  public ListOrdersResponseDataInner updatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this ListOrdersResponse_data_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListOrdersResponseDataInner listOrdersResponseDataInner = (ListOrdersResponseDataInner) o;
    return Objects.equals(this.cancellationReason, listOrdersResponseDataInner.cancellationReason) &&
        Objects.equals(this.carrier, listOrdersResponseDataInner.carrier) &&
        Objects.equals(this.catalogItemId, listOrdersResponseDataInner.catalogItemId) &&
        Objects.equals(this.practiceId, listOrdersResponseDataInner.practiceId) &&
        Objects.equals(this.compounderId, listOrdersResponseDataInner.compounderId) &&
        Objects.equals(this.createdAt, listOrdersResponseDataInner.createdAt) &&
        Objects.equals(this.currency, listOrdersResponseDataInner.currency) &&
        Objects.equals(this.directions, listOrdersResponseDataInner.directions) &&
        Objects.equals(this.dosageForm, listOrdersResponseDataInner.dosageForm) &&
        Objects.equals(this.externalOrderId, listOrdersResponseDataInner.externalOrderId) &&
        Objects.equals(this.externalSubmissionAttempted, listOrdersResponseDataInner.externalSubmissionAttempted) &&
        Objects.equals(this.externalSubmissionBlockedReason, listOrdersResponseDataInner.externalSubmissionBlockedReason) &&
        Objects.equals(this.id, listOrdersResponseDataInner.id) &&
        Objects.equals(this.livemode, listOrdersResponseDataInner.livemode) &&
        Objects.equals(this.medicationName, listOrdersResponseDataInner.medicationName) &&
        Objects.equals(this.patientExternalId, listOrdersResponseDataInner.patientExternalId) &&
        Objects.equals(this.patientName, listOrdersResponseDataInner.patientName) &&
        Objects.equals(this.patientState, listOrdersResponseDataInner.patientState) &&
        Objects.equals(this.prescriberName, listOrdersResponseDataInner.prescriberName) &&
        Objects.equals(this.prescriberNpi, listOrdersResponseDataInner.prescriberNpi) &&
        Objects.equals(this.quantity, listOrdersResponseDataInner.quantity) &&
        Objects.equals(this.quoteCents, listOrdersResponseDataInner.quoteCents) &&
        Objects.equals(this._object, listOrdersResponseDataInner._object) &&
        Objects.equals(this.replacesOrderId, listOrdersResponseDataInner.replacesOrderId) &&
        Objects.equals(this.routing, listOrdersResponseDataInner.routing) &&
        Objects.equals(this.status, listOrdersResponseDataInner.status) &&
        Objects.equals(this.strength, listOrdersResponseDataInner.strength) &&
        Objects.equals(this.trackingNumber, listOrdersResponseDataInner.trackingNumber) &&
        Objects.equals(this.shippedAt, listOrdersResponseDataInner.shippedAt) &&
        Objects.equals(this.deliveredAt, listOrdersResponseDataInner.deliveredAt) &&
        Objects.equals(this.updatedAt, listOrdersResponseDataInner.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cancellationReason, carrier, catalogItemId, practiceId, compounderId, createdAt, currency, directions, dosageForm, externalOrderId, externalSubmissionAttempted, externalSubmissionBlockedReason, id, livemode, medicationName, patientExternalId, patientName, patientState, prescriberName, prescriberNpi, quantity, quoteCents, _object, replacesOrderId, routing, status, strength, trackingNumber, shippedAt, deliveredAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListOrdersResponseDataInner {\n");
    sb.append("    cancellationReason: ").append(toIndentedString(cancellationReason)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    catalogItemId: ").append(toIndentedString(catalogItemId)).append("\n");
    sb.append("    practiceId: ").append(toIndentedString(practiceId)).append("\n");
    sb.append("    compounderId: ").append(toIndentedString(compounderId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    directions: ").append(toIndentedString(directions)).append("\n");
    sb.append("    dosageForm: ").append(toIndentedString(dosageForm)).append("\n");
    sb.append("    externalOrderId: ").append(toIndentedString(externalOrderId)).append("\n");
    sb.append("    externalSubmissionAttempted: ").append(toIndentedString(externalSubmissionAttempted)).append("\n");
    sb.append("    externalSubmissionBlockedReason: ").append(toIndentedString(externalSubmissionBlockedReason)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    medicationName: ").append(toIndentedString(medicationName)).append("\n");
    sb.append("    patientExternalId: ").append(toIndentedString(patientExternalId)).append("\n");
    sb.append("    patientName: ").append(toIndentedString(patientName)).append("\n");
    sb.append("    patientState: ").append(toIndentedString(patientState)).append("\n");
    sb.append("    prescriberName: ").append(toIndentedString(prescriberName)).append("\n");
    sb.append("    prescriberNpi: ").append(toIndentedString(prescriberNpi)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    quoteCents: ").append(toIndentedString(quoteCents)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    replacesOrderId: ").append(toIndentedString(replacesOrderId)).append("\n");
    sb.append("    routing: ").append(toIndentedString(routing)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    strength: ").append(toIndentedString(strength)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    shippedAt: ").append(toIndentedString(shippedAt)).append("\n");
    sb.append("    deliveredAt: ").append(toIndentedString(deliveredAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `cancellationReason` to the URL query string
    if (getCancellationReason() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scancellationReason%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCancellationReason()))));
    }

    // add `carrier` to the URL query string
    if (getCarrier() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scarrier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCarrier()))));
    }

    // add `catalogItemId` to the URL query string
    if (getCatalogItemId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scatalogItemId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCatalogItemId()))));
    }

    // add `practiceId` to the URL query string
    if (getPracticeId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spracticeId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPracticeId()))));
    }

    // add `compounderId` to the URL query string
    if (getCompounderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scompounderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompounderId()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `directions` to the URL query string
    if (getDirections() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdirections%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDirections()))));
    }

    // add `dosageForm` to the URL query string
    if (getDosageForm() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdosageForm%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDosageForm()))));
    }

    // add `externalOrderId` to the URL query string
    if (getExternalOrderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexternalOrderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExternalOrderId()))));
    }

    // add `externalSubmissionAttempted` to the URL query string
    if (getExternalSubmissionAttempted() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexternalSubmissionAttempted%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExternalSubmissionAttempted()))));
    }

    // add `externalSubmissionBlockedReason` to the URL query string
    if (getExternalSubmissionBlockedReason() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexternalSubmissionBlockedReason%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExternalSubmissionBlockedReason()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `livemode` to the URL query string
    if (getLivemode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slivemode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLivemode()))));
    }

    // add `medicationName` to the URL query string
    if (getMedicationName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smedicationName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMedicationName()))));
    }

    // add `patientExternalId` to the URL query string
    if (getPatientExternalId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spatientExternalId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPatientExternalId()))));
    }

    // add `patientName` to the URL query string
    if (getPatientName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spatientName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPatientName()))));
    }

    // add `patientState` to the URL query string
    if (getPatientState() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spatientState%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPatientState()))));
    }

    // add `prescriberName` to the URL query string
    if (getPrescriberName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprescriberName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrescriberName()))));
    }

    // add `prescriberNpi` to the URL query string
    if (getPrescriberNpi() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprescriberNpi%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrescriberNpi()))));
    }

    // add `quantity` to the URL query string
    if (getQuantity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squantity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuantity()))));
    }

    // add `quoteCents` to the URL query string
    if (getQuoteCents() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squoteCents%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuoteCents()))));
    }

    // add `object` to the URL query string
    if (getObject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sobject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObject()))));
    }

    // add `replacesOrderId` to the URL query string
    if (getReplacesOrderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreplacesOrderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReplacesOrderId()))));
    }

    // add `routing` to the URL query string
    if (getRouting() != null) {
      joiner.add(getRouting().toUrlQueryString(prefix + "routing" + suffix));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `strength` to the URL query string
    if (getStrength() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstrength%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStrength()))));
    }

    // add `trackingNumber` to the URL query string
    if (getTrackingNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%strackingNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTrackingNumber()))));
    }

    // add `shippedAt` to the URL query string
    if (getShippedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshippedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShippedAt()))));
    }

    // add `deliveredAt` to the URL query string
    if (getDeliveredAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeliveredAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveredAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

