/*
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * ListWebhookEvents200ResponseEventsInner
 */
@JsonPropertyOrder({
  ListWebhookEvents200ResponseEventsInner.JSON_PROPERTY_CREATED_AT,
  ListWebhookEvents200ResponseEventsInner.JSON_PROPERTY_EVENT_TYPE,
  ListWebhookEvents200ResponseEventsInner.JSON_PROPERTY_ID,
  ListWebhookEvents200ResponseEventsInner.JSON_PROPERTY_LIVEMODE,
  ListWebhookEvents200ResponseEventsInner.JSON_PROPERTY_OBJECT_ID,
  ListWebhookEvents200ResponseEventsInner.JSON_PROPERTY_OBJECT_TYPE,
  ListWebhookEvents200ResponseEventsInner.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class ListWebhookEvents200ResponseEventsInner {
  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @javax.annotation.Nullable
  private String eventType;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_LIVEMODE = "livemode";
  @javax.annotation.Nonnull
  private Boolean livemode;

  public static final String JSON_PROPERTY_OBJECT_ID = "objectId";
  @javax.annotation.Nullable
  private String objectId;

  public static final String JSON_PROPERTY_OBJECT_TYPE = "objectType";
  @javax.annotation.Nullable
  private String objectType;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nullable
  private String updatedAt;

  public ListWebhookEvents200ResponseEventsInner() {
  }

  public ListWebhookEvents200ResponseEventsInner createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public ListWebhookEvents200ResponseEventsInner eventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }


  public ListWebhookEvents200ResponseEventsInner id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ListWebhookEvents200ResponseEventsInner livemode(@javax.annotation.Nonnull Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

  /**
   * Get livemode
   * @return livemode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIVEMODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getLivemode() {
    return livemode;
  }


  @JsonProperty(value = JSON_PROPERTY_LIVEMODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLivemode(@javax.annotation.Nonnull Boolean livemode) {
    this.livemode = livemode;
  }


  public ListWebhookEvents200ResponseEventsInner objectId(@javax.annotation.Nullable String objectId) {
    this.objectId = objectId;
    return this;
  }

  /**
   * Get objectId
   * @return objectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getObjectId() {
    return objectId;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectId(@javax.annotation.Nullable String objectId) {
    this.objectId = objectId;
  }


  public ListWebhookEvents200ResponseEventsInner objectType(@javax.annotation.Nullable String objectType) {
    this.objectType = objectType;
    return this;
  }

  /**
   * Get objectType
   * @return objectType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBJECT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getObjectType() {
    return objectType;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectType(@javax.annotation.Nullable String objectType) {
    this.objectType = objectType;
  }


  public ListWebhookEvents200ResponseEventsInner updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this listWebhookEvents_200_response_events_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListWebhookEvents200ResponseEventsInner listWebhookEvents200ResponseEventsInner = (ListWebhookEvents200ResponseEventsInner) o;
    return Objects.equals(this.createdAt, listWebhookEvents200ResponseEventsInner.createdAt) &&
        Objects.equals(this.eventType, listWebhookEvents200ResponseEventsInner.eventType) &&
        Objects.equals(this.id, listWebhookEvents200ResponseEventsInner.id) &&
        Objects.equals(this.livemode, listWebhookEvents200ResponseEventsInner.livemode) &&
        Objects.equals(this.objectId, listWebhookEvents200ResponseEventsInner.objectId) &&
        Objects.equals(this.objectType, listWebhookEvents200ResponseEventsInner.objectType) &&
        Objects.equals(this.updatedAt, listWebhookEvents200ResponseEventsInner.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, eventType, id, livemode, objectId, objectType, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListWebhookEvents200ResponseEventsInner {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%seventType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `livemode` to the URL query string
    if (getLivemode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slivemode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLivemode()))));
    }

    // add `objectId` to the URL query string
    if (getObjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sobjectId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObjectId()))));
    }

    // add `objectType` to the URL query string
    if (getObjectType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sobjectType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObjectType()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

