/*
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.joinaffinity.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import ai.joinaffinity.sdk.model.CreateOrderRequestAnyOfPatientAddress;
import ai.joinaffinity.sdk.model.CreatePracticeRequestAttestations;
import ai.joinaffinity.sdk.model.CreatePracticeRequestComplianceContact;
import ai.joinaffinity.sdk.model.CreatePracticeRequestPrescribersInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import ai.joinaffinity.sdk.ApiClient;
/**
 * UpdatePracticeRequest
 */
@JsonPropertyOrder({
  UpdatePracticeRequest.JSON_PROPERTY_ADDRESS,
  UpdatePracticeRequest.JSON_PROPERTY_ATTESTATIONS,
  UpdatePracticeRequest.JSON_PROPERTY_COMPLIANCE_CONTACT,
  UpdatePracticeRequest.JSON_PROPERTY_EXTERNAL_ID,
  UpdatePracticeRequest.JSON_PROPERTY_LEGAL_NAME,
  UpdatePracticeRequest.JSON_PROPERTY_METADATA,
  UpdatePracticeRequest.JSON_PROPERTY_NAME,
  UpdatePracticeRequest.JSON_PROPERTY_PRESCRIBERS,
  UpdatePracticeRequest.JSON_PROPERTY_PRIMARY_CONTACT,
  UpdatePracticeRequest.JSON_PROPERTY_SUPPORT_EMAIL,
  UpdatePracticeRequest.JSON_PROPERTY_SUPPORT_PHONE,
  UpdatePracticeRequest.JSON_PROPERTY_TIMEZONE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class UpdatePracticeRequest {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private CreateOrderRequestAnyOfPatientAddress address;

  public static final String JSON_PROPERTY_ATTESTATIONS = "attestations";
  @javax.annotation.Nullable
  private CreatePracticeRequestAttestations attestations;

  public static final String JSON_PROPERTY_COMPLIANCE_CONTACT = "complianceContact";
  private JsonNullable<CreatePracticeRequestComplianceContact> complianceContact = JsonNullable.<CreatePracticeRequestComplianceContact>undefined();

  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  private JsonNullable<String> externalId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LEGAL_NAME = "legalName";
  private JsonNullable<String> legalName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PRESCRIBERS = "prescribers";
  @javax.annotation.Nullable
  private List<CreatePracticeRequestPrescribersInner> prescribers = new ArrayList<>();

  public static final String JSON_PROPERTY_PRIMARY_CONTACT = "primaryContact";
  private JsonNullable<CreatePracticeRequestComplianceContact> primaryContact = JsonNullable.<CreatePracticeRequestComplianceContact>undefined();

  public static final String JSON_PROPERTY_SUPPORT_EMAIL = "supportEmail";
  private JsonNullable<String> supportEmail = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SUPPORT_PHONE = "supportPhone";
  private JsonNullable<String> supportPhone = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  @javax.annotation.Nullable
  private String timezone;

  public UpdatePracticeRequest() {
  }

  public UpdatePracticeRequest address(@javax.annotation.Nullable CreateOrderRequestAnyOfPatientAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateOrderRequestAnyOfPatientAddress getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable CreateOrderRequestAnyOfPatientAddress address) {
    this.address = address;
  }


  public UpdatePracticeRequest attestations(@javax.annotation.Nullable CreatePracticeRequestAttestations attestations) {
    this.attestations = attestations;
    return this;
  }

  /**
   * Get attestations
   * @return attestations
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATTESTATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreatePracticeRequestAttestations getAttestations() {
    return attestations;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTESTATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttestations(@javax.annotation.Nullable CreatePracticeRequestAttestations attestations) {
    this.attestations = attestations;
  }


  public UpdatePracticeRequest complianceContact(@javax.annotation.Nullable CreatePracticeRequestComplianceContact complianceContact) {
    this.complianceContact = JsonNullable.<CreatePracticeRequestComplianceContact>of(complianceContact);
    return this;
  }

  /**
   * Get complianceContact
   * @return complianceContact
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public CreatePracticeRequestComplianceContact getComplianceContact() {
        return complianceContact.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COMPLIANCE_CONTACT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CreatePracticeRequestComplianceContact> getComplianceContact_JsonNullable() {
    return complianceContact;
  }

  @JsonProperty(JSON_PROPERTY_COMPLIANCE_CONTACT)
  public void setComplianceContact_JsonNullable(JsonNullable<CreatePracticeRequestComplianceContact> complianceContact) {
    this.complianceContact = complianceContact;
  }

  public void setComplianceContact(@javax.annotation.Nullable CreatePracticeRequestComplianceContact complianceContact) {
    this.complianceContact = JsonNullable.<CreatePracticeRequestComplianceContact>of(complianceContact);
  }


  public UpdatePracticeRequest externalId(@javax.annotation.Nullable String externalId) {
    this.externalId = JsonNullable.<String>of(externalId);
    return this;
  }

  /**
   * Get externalId
   * @return externalId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getExternalId() {
        return externalId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExternalId_JsonNullable() {
    return externalId;
  }

  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  public void setExternalId_JsonNullable(JsonNullable<String> externalId) {
    this.externalId = externalId;
  }

  public void setExternalId(@javax.annotation.Nullable String externalId) {
    this.externalId = JsonNullable.<String>of(externalId);
  }


  public UpdatePracticeRequest legalName(@javax.annotation.Nullable String legalName) {
    this.legalName = JsonNullable.<String>of(legalName);
    return this;
  }

  /**
   * Get legalName
   * @return legalName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getLegalName() {
        return legalName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LEGAL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLegalName_JsonNullable() {
    return legalName;
  }

  @JsonProperty(JSON_PROPERTY_LEGAL_NAME)
  public void setLegalName_JsonNullable(JsonNullable<String> legalName) {
    this.legalName = legalName;
  }

  public void setLegalName(@javax.annotation.Nullable String legalName) {
    this.legalName = JsonNullable.<String>of(legalName);
  }


  public UpdatePracticeRequest metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public UpdatePracticeRequest putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public UpdatePracticeRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public UpdatePracticeRequest prescribers(@javax.annotation.Nullable List<CreatePracticeRequestPrescribersInner> prescribers) {
    this.prescribers = prescribers;
    return this;
  }

  public UpdatePracticeRequest addPrescribersItem(CreatePracticeRequestPrescribersInner prescribersItem) {
    if (this.prescribers == null) {
      this.prescribers = new ArrayList<>();
    }
    this.prescribers.add(prescribersItem);
    return this;
  }

  /**
   * Get prescribers
   * @return prescribers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRESCRIBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<CreatePracticeRequestPrescribersInner> getPrescribers() {
    return prescribers;
  }


  @JsonProperty(value = JSON_PROPERTY_PRESCRIBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrescribers(@javax.annotation.Nullable List<CreatePracticeRequestPrescribersInner> prescribers) {
    this.prescribers = prescribers;
  }


  public UpdatePracticeRequest primaryContact(@javax.annotation.Nullable CreatePracticeRequestComplianceContact primaryContact) {
    this.primaryContact = JsonNullable.<CreatePracticeRequestComplianceContact>of(primaryContact);
    return this;
  }

  /**
   * Get primaryContact
   * @return primaryContact
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public CreatePracticeRequestComplianceContact getPrimaryContact() {
        return primaryContact.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PRIMARY_CONTACT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CreatePracticeRequestComplianceContact> getPrimaryContact_JsonNullable() {
    return primaryContact;
  }

  @JsonProperty(JSON_PROPERTY_PRIMARY_CONTACT)
  public void setPrimaryContact_JsonNullable(JsonNullable<CreatePracticeRequestComplianceContact> primaryContact) {
    this.primaryContact = primaryContact;
  }

  public void setPrimaryContact(@javax.annotation.Nullable CreatePracticeRequestComplianceContact primaryContact) {
    this.primaryContact = JsonNullable.<CreatePracticeRequestComplianceContact>of(primaryContact);
  }


  public UpdatePracticeRequest supportEmail(@javax.annotation.Nullable String supportEmail) {
    this.supportEmail = JsonNullable.<String>of(supportEmail);
    return this;
  }

  /**
   * Get supportEmail
   * @return supportEmail
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getSupportEmail() {
        return supportEmail.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SUPPORT_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSupportEmail_JsonNullable() {
    return supportEmail;
  }

  @JsonProperty(JSON_PROPERTY_SUPPORT_EMAIL)
  public void setSupportEmail_JsonNullable(JsonNullable<String> supportEmail) {
    this.supportEmail = supportEmail;
  }

  public void setSupportEmail(@javax.annotation.Nullable String supportEmail) {
    this.supportEmail = JsonNullable.<String>of(supportEmail);
  }


  public UpdatePracticeRequest supportPhone(@javax.annotation.Nullable String supportPhone) {
    this.supportPhone = JsonNullable.<String>of(supportPhone);
    return this;
  }

  /**
   * Get supportPhone
   * @return supportPhone
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getSupportPhone() {
        return supportPhone.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SUPPORT_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSupportPhone_JsonNullable() {
    return supportPhone;
  }

  @JsonProperty(JSON_PROPERTY_SUPPORT_PHONE)
  public void setSupportPhone_JsonNullable(JsonNullable<String> supportPhone) {
    this.supportPhone = supportPhone;
  }

  public void setSupportPhone(@javax.annotation.Nullable String supportPhone) {
    this.supportPhone = JsonNullable.<String>of(supportPhone);
  }


  public UpdatePracticeRequest timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Get timezone
   * @return timezone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimezone() {
    return timezone;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }


  /**
   * Return true if this UpdatePracticeRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePracticeRequest updatePracticeRequest = (UpdatePracticeRequest) o;
    return Objects.equals(this.address, updatePracticeRequest.address) &&
        Objects.equals(this.attestations, updatePracticeRequest.attestations) &&
        equalsNullable(this.complianceContact, updatePracticeRequest.complianceContact) &&
        equalsNullable(this.externalId, updatePracticeRequest.externalId) &&
        equalsNullable(this.legalName, updatePracticeRequest.legalName) &&
        Objects.equals(this.metadata, updatePracticeRequest.metadata) &&
        Objects.equals(this.name, updatePracticeRequest.name) &&
        Objects.equals(this.prescribers, updatePracticeRequest.prescribers) &&
        equalsNullable(this.primaryContact, updatePracticeRequest.primaryContact) &&
        equalsNullable(this.supportEmail, updatePracticeRequest.supportEmail) &&
        equalsNullable(this.supportPhone, updatePracticeRequest.supportPhone) &&
        Objects.equals(this.timezone, updatePracticeRequest.timezone);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, attestations, hashCodeNullable(complianceContact), hashCodeNullable(externalId), hashCodeNullable(legalName), metadata, name, prescribers, hashCodeNullable(primaryContact), hashCodeNullable(supportEmail), hashCodeNullable(supportPhone), timezone);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePracticeRequest {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    attestations: ").append(toIndentedString(attestations)).append("\n");
    sb.append("    complianceContact: ").append(toIndentedString(complianceContact)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    legalName: ").append(toIndentedString(legalName)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    prescribers: ").append(toIndentedString(prescribers)).append("\n");
    sb.append("    primaryContact: ").append(toIndentedString(primaryContact)).append("\n");
    sb.append("    supportEmail: ").append(toIndentedString(supportEmail)).append("\n");
    sb.append("    supportPhone: ").append(toIndentedString(supportPhone)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(getAddress().toUrlQueryString(prefix + "address" + suffix));
    }

    // add `attestations` to the URL query string
    if (getAttestations() != null) {
      joiner.add(getAttestations().toUrlQueryString(prefix + "attestations" + suffix));
    }

    // add `complianceContact` to the URL query string
    if (getComplianceContact() != null) {
      joiner.add(getComplianceContact().toUrlQueryString(prefix + "complianceContact" + suffix));
    }

    // add `externalId` to the URL query string
    if (getExternalId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexternalId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExternalId()))));
    }

    // add `legalName` to the URL query string
    if (getLegalName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slegalName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLegalName()))));
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      for (String _key : getMetadata().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%smetadata%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getMetadata().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getMetadata().get(_key)))));
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `prescribers` to the URL query string
    if (getPrescribers() != null) {
      for (int i = 0; i < getPrescribers().size(); i++) {
        if (getPrescribers().get(i) != null) {
          joiner.add(getPrescribers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sprescribers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `primaryContact` to the URL query string
    if (getPrimaryContact() != null) {
      joiner.add(getPrimaryContact().toUrlQueryString(prefix + "primaryContact" + suffix));
    }

    // add `supportEmail` to the URL query string
    if (getSupportEmail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssupportEmail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSupportEmail()))));
    }

    // add `supportPhone` to the URL query string
    if (getSupportPhone() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssupportPhone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSupportPhone()))));
    }

    // add `timezone` to the URL query string
    if (getTimezone() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimezone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimezone()))));
    }

    return joiner.toString();
  }
}

